//! Bulk operations for Attribute entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateAttributeDto;
use crate::application::service::AttributeService;
use crate::domain::entity::Attribute;

/// Bulk operation handler for Attribute entities.
///
/// Wraps `AttributeService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type AttributeBulkService = GenericBulkService<Attribute, CreateAttributeDto, AttributeService>;

// <<< CUSTOM
// END CUSTOM
