//! Bulk operations for AttributeValue entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateAttributeValueDto;
use crate::application::service::AttributeValueService;
use crate::domain::entity::AttributeValue;

/// Bulk operation handler for AttributeValue entities.
///
/// Wraps `AttributeValueService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type AttributeValueBulkService = GenericBulkService<AttributeValue, CreateAttributeValueDto, AttributeValueService>;

// <<< CUSTOM
// END CUSTOM
