//! Bulk operations for Brand entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateBrandDto;
use crate::application::service::BrandService;
use crate::domain::entity::Brand;

/// Bulk operation handler for Brand entities.
///
/// Wraps `BrandService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type BrandBulkService = GenericBulkService<Brand, CreateBrandDto, BrandService>;

// <<< CUSTOM
// END CUSTOM
