//! Bulk operations for Item entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateItemDto;
use crate::application::service::ItemService;
use crate::domain::entity::Item;

/// Bulk operation handler for Item entities.
///
/// Wraps `ItemService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type ItemBulkService = GenericBulkService<Item, CreateItemDto, ItemService>;

// <<< CUSTOM
// END CUSTOM
