//! Bulk operations
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::*;

pub mod attribute_bulk;
pub mod attribute_value_bulk;
pub mod brand_bulk;
pub mod item_bulk;
pub mod item_group_bulk;
pub mod item_variant_bulk;
pub mod uom_bulk;
pub mod uom_conversion_bulk;

pub use attribute_bulk::AttributeBulkService;
pub use attribute_value_bulk::AttributeValueBulkService;
pub use brand_bulk::BrandBulkService;
pub use item_bulk::ItemBulkService;
pub use item_group_bulk::ItemGroupBulkService;
pub use item_variant_bulk::ItemVariantBulkService;
pub use uom_bulk::UomBulkService;
pub use uom_conversion_bulk::UomConversionBulkService;

// <<< CUSTOM
// END CUSTOM
