//! Bulk operations for UomConversion entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateUomConversionDto;
use crate::application::service::UomConversionService;
use crate::domain::entity::UomConversion;

/// Bulk operation handler for UomConversion entities.
///
/// Wraps `UomConversionService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type UomConversionBulkService = GenericBulkService<UomConversion, CreateUomConversionDto, UomConversionService>;

// <<< CUSTOM
// END CUSTOM
