//! Bulk operations for Uom entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateUomDto;
use crate::application::service::UomService;
use crate::domain::entity::Uom;

/// Bulk operation handler for Uom entities.
///
/// Wraps `UomService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type UomBulkService = GenericBulkService<Uom, CreateUomDto, UomService>;

// <<< CUSTOM
// END CUSTOM
