//! Attribute DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Attribute;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::AttributeType;
use crate::domain::entity::CatalogStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Attribute
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateAttributeDto {
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub code: String,
    #[cfg_attr(feature = "validation", validate(length(max = 100)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[serde(alias = "attribute_type")]
    pub attribute_type: AttributeType,
    pub status: CatalogStatus,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Attribute
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateAttributeDto {
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub code: String,
    #[cfg_attr(feature = "validation", validate(length(max = 100)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[serde(alias = "attribute_type")]
    pub attribute_type: AttributeType,
    pub status: CatalogStatus,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Attribute
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchAttributeDto {
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 100)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "attribute_type")]
    pub attribute_type: Option<AttributeType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<CatalogStatus>,
}

impl PatchAttributeDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.code.is_some() || self.name.is_some() || self.attribute_type.is_some() || self.status.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Attribute entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AttributeResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub code: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    pub attribute_type: AttributeType,
    pub status: CatalogStatus,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Attribute entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AttributeListResponseDto {
    /// List of items
    pub items: Vec<AttributeResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl AttributeListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<AttributeResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AttributeSummaryDto {
    pub id: Uuid,
    pub code: String,
    pub name: String,
    pub attribute_type: AttributeType,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Attribute> for AttributeResponseDto {
    fn from(entity: Attribute) -> Self {
        Self {
            id: entity.id,
            code: entity.code,
            name: entity.name,
            attribute_type: entity.attribute_type,
            status: entity.status,
            metadata: entity.metadata,
        }
    }
}

impl From<Attribute> for AttributeSummaryDto {
    fn from(entity: Attribute) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            code: entity.code,
            name: entity.name,
            attribute_type: entity.attribute_type,
            created_at,
        }
    }
}

impl From<CreateAttributeDto> for Attribute {
    fn from(dto: CreateAttributeDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            code: dto.code,
            name: dto.name,
            attribute_type: dto.attribute_type,
            status: dto.status,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Attribute> for AttributeResponseDto {
    fn from(entity: &Attribute) -> Self {
        Self {
            id: entity.id.clone(),
            code: entity.code.clone(),
            name: entity.name.clone(),
            attribute_type: entity.attribute_type.clone(),
            status: entity.status.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateAttributeDto> for Attribute {
    fn from_create_dto(dto: CreateAttributeDto) -> backbone_core::ServiceResult<Self> {
        Ok(Attribute::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateAttributeDto> for Attribute {
    fn apply_update(mut self, dto: UpdateAttributeDto) -> backbone_core::ServiceResult<Self> {
        self.code = dto.code;
        self.name = dto.name;
        self.attribute_type = dto.attribute_type;
        self.status = dto.status;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Attribute here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
