//! Item DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Item;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::CatalogStatus;
use crate::domain::entity::ItemType;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Item
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateItemDto {
    #[cfg_attr(feature = "validation", validate(length(max = 60)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "item_code")]
    pub item_code: String,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "validation", validate(length(max = 2000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 60)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub barcode: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "brand_id")]
    pub brand_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "item_group_id")]
    pub item_group_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "default_uom_id")]
    pub default_uom_id: Uuid,
    #[serde(alias = "item_type")]
    pub item_type: ItemType,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_sales_item")]
    pub is_sales_item: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_purchase_item")]
    pub is_purchase_item: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_stock_item")]
    pub is_stock_item: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "has_variants")]
    pub has_variants: bool,
    #[cfg_attr(feature = "validation", validate(length(max = 20)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "hsn_code")]
    pub hsn_code: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sni: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_taxable")]
    pub is_taxable: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "weight_per_unit")]
    pub weight_per_unit: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "shelf_life_days")]
    pub shelf_life_days: Option<i32>,
    pub tags: serde_json::Value,
    pub data: serde_json::Value,
    pub status: CatalogStatus,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Item
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateItemDto {
    #[cfg_attr(feature = "validation", validate(length(max = 60)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "item_code")]
    pub item_code: String,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "validation", validate(length(max = 2000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 60)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub barcode: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "brand_id")]
    pub brand_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "item_group_id")]
    pub item_group_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "default_uom_id")]
    pub default_uom_id: Uuid,
    #[serde(alias = "item_type")]
    pub item_type: ItemType,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_sales_item")]
    pub is_sales_item: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_purchase_item")]
    pub is_purchase_item: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_stock_item")]
    pub is_stock_item: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "has_variants")]
    pub has_variants: bool,
    #[cfg_attr(feature = "validation", validate(length(max = 20)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "hsn_code")]
    pub hsn_code: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sni: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_taxable")]
    pub is_taxable: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "weight_per_unit")]
    pub weight_per_unit: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "shelf_life_days")]
    pub shelf_life_days: Option<i32>,
    pub tags: serde_json::Value,
    pub data: serde_json::Value,
    pub status: CatalogStatus,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Item
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchItemDto {
    #[cfg_attr(feature = "validation", validate(length(max = 60)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "item_code")]
    pub item_code: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 2000)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 60)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub barcode: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "brand_id")]
    pub brand_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "item_group_id")]
    pub item_group_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "default_uom_id")]
    pub default_uom_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "item_type")]
    pub item_type: Option<ItemType>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_sales_item")]
    pub is_sales_item: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_purchase_item")]
    pub is_purchase_item: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_stock_item")]
    pub is_stock_item: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "has_variants")]
    pub has_variants: Option<bool>,
    #[cfg_attr(feature = "validation", validate(length(max = 20)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "hsn_code")]
    pub hsn_code: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sni: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_taxable")]
    pub is_taxable: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "weight_per_unit")]
    pub weight_per_unit: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "shelf_life_days")]
    pub shelf_life_days: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tags: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<CatalogStatus>,
}

impl PatchItemDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.item_code.is_some() || self.name.is_some() || self.description.is_some() || self.barcode.is_some() || self.brand_id.is_some() || self.item_group_id.is_some() || self.default_uom_id.is_some() || self.item_type.is_some() || self.is_sales_item.is_some() || self.is_purchase_item.is_some() || self.is_stock_item.is_some() || self.has_variants.is_some() || self.hsn_code.is_some() || self.sni.is_some() || self.is_taxable.is_some() || self.weight_per_unit.is_some() || self.shelf_life_days.is_some() || self.tags.is_some() || self.data.is_some() || self.status.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Item entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ItemResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub item_code: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    pub description: Option<String>,
    pub barcode: Option<String>,
    pub brand_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub item_group_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub default_uom_id: Uuid,
    pub item_type: ItemType,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_sales_item: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_purchase_item: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_stock_item: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub has_variants: bool,
    pub hsn_code: Option<String>,
    pub sni: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_taxable: bool,
    pub weight_per_unit: Option<Decimal>,
    pub shelf_life_days: Option<i32>,
    pub tags: serde_json::Value,
    pub data: serde_json::Value,
    pub status: CatalogStatus,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Item entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ItemListResponseDto {
    /// List of items
    pub items: Vec<ItemResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl ItemListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<ItemResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ItemSummaryDto {
    pub id: Uuid,
    pub item_code: String,
    pub name: String,
    pub description: Option<String>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Item> for ItemResponseDto {
    fn from(entity: Item) -> Self {
        Self {
            id: entity.id,
            item_code: entity.item_code,
            name: entity.name,
            description: entity.description,
            barcode: entity.barcode,
            brand_id: entity.brand_id,
            item_group_id: entity.item_group_id,
            default_uom_id: entity.default_uom_id,
            item_type: entity.item_type,
            is_sales_item: entity.is_sales_item,
            is_purchase_item: entity.is_purchase_item,
            is_stock_item: entity.is_stock_item,
            has_variants: entity.has_variants,
            hsn_code: entity.hsn_code,
            sni: entity.sni,
            is_taxable: entity.is_taxable,
            weight_per_unit: entity.weight_per_unit,
            shelf_life_days: entity.shelf_life_days,
            tags: entity.tags,
            data: entity.data,
            status: entity.status,
            metadata: entity.metadata,
        }
    }
}

impl From<Item> for ItemSummaryDto {
    fn from(entity: Item) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            item_code: entity.item_code,
            name: entity.name,
            description: entity.description,
            created_at,
        }
    }
}

impl From<CreateItemDto> for Item {
    fn from(dto: CreateItemDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            item_code: dto.item_code,
            name: dto.name,
            description: dto.description,
            barcode: dto.barcode,
            brand_id: dto.brand_id,
            item_group_id: dto.item_group_id,
            default_uom_id: dto.default_uom_id,
            item_type: dto.item_type,
            is_sales_item: dto.is_sales_item,
            is_purchase_item: dto.is_purchase_item,
            is_stock_item: dto.is_stock_item,
            has_variants: dto.has_variants,
            hsn_code: dto.hsn_code,
            sni: dto.sni,
            is_taxable: dto.is_taxable,
            weight_per_unit: dto.weight_per_unit,
            shelf_life_days: dto.shelf_life_days,
            tags: dto.tags,
            data: dto.data,
            status: dto.status,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Item> for ItemResponseDto {
    fn from(entity: &Item) -> Self {
        Self {
            id: entity.id.clone(),
            item_code: entity.item_code.clone(),
            name: entity.name.clone(),
            description: entity.description.clone(),
            barcode: entity.barcode.clone(),
            brand_id: entity.brand_id.clone(),
            item_group_id: entity.item_group_id.clone(),
            default_uom_id: entity.default_uom_id.clone(),
            item_type: entity.item_type.clone(),
            is_sales_item: entity.is_sales_item.clone(),
            is_purchase_item: entity.is_purchase_item.clone(),
            is_stock_item: entity.is_stock_item.clone(),
            has_variants: entity.has_variants.clone(),
            hsn_code: entity.hsn_code.clone(),
            sni: entity.sni.clone(),
            is_taxable: entity.is_taxable.clone(),
            weight_per_unit: entity.weight_per_unit.clone(),
            shelf_life_days: entity.shelf_life_days.clone(),
            tags: entity.tags.clone(),
            data: entity.data.clone(),
            status: entity.status.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateItemDto> for Item {
    fn from_create_dto(dto: CreateItemDto) -> backbone_core::ServiceResult<Self> {
        Ok(Item::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateItemDto> for Item {
    fn apply_update(mut self, dto: UpdateItemDto) -> backbone_core::ServiceResult<Self> {
        self.item_code = dto.item_code;
        self.name = dto.name;
        self.description = dto.description;
        self.barcode = dto.barcode;
        self.brand_id = dto.brand_id;
        self.item_group_id = dto.item_group_id;
        self.default_uom_id = dto.default_uom_id;
        self.item_type = dto.item_type;
        self.is_sales_item = dto.is_sales_item;
        self.is_purchase_item = dto.is_purchase_item;
        self.is_stock_item = dto.is_stock_item;
        self.has_variants = dto.has_variants;
        self.hsn_code = dto.hsn_code;
        self.sni = dto.sni;
        self.is_taxable = dto.is_taxable;
        self.weight_per_unit = dto.weight_per_unit;
        self.shelf_life_days = dto.shelf_life_days;
        self.tags = dto.tags;
        self.data = dto.data;
        self.status = dto.status;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Item here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
