//! UomConversion DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::UomConversion;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new UomConversion
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateUomConversionDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "from_uom_id")]
    pub from_uom_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "to_uom_id")]
    pub to_uom_id: Uuid,
    pub factor: Decimal,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a UomConversion
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateUomConversionDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "from_uom_id")]
    pub from_uom_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "to_uom_id")]
    pub to_uom_id: Uuid,
    pub factor: Decimal,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a UomConversion
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchUomConversionDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "from_uom_id")]
    pub from_uom_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "to_uom_id")]
    pub to_uom_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub factor: Option<Decimal>,
}

impl PatchUomConversionDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.from_uom_id.is_some() || self.to_uom_id.is_some() || self.factor.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for UomConversion entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct UomConversionResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub from_uom_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub to_uom_id: Uuid,
    pub factor: Decimal,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for UomConversion entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct UomConversionListResponseDto {
    /// List of items
    pub items: Vec<UomConversionResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl UomConversionListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<UomConversionResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct UomConversionSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub from_uom_id: Uuid,
    pub to_uom_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<UomConversion> for UomConversionResponseDto {
    fn from(entity: UomConversion) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            from_uom_id: entity.from_uom_id,
            to_uom_id: entity.to_uom_id,
            factor: entity.factor,
            metadata: entity.metadata,
        }
    }
}

impl From<UomConversion> for UomConversionSummaryDto {
    fn from(entity: UomConversion) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            from_uom_id: entity.from_uom_id,
            to_uom_id: entity.to_uom_id,
            created_at,
        }
    }
}

impl From<CreateUomConversionDto> for UomConversion {
    fn from(dto: CreateUomConversionDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            from_uom_id: dto.from_uom_id,
            to_uom_id: dto.to_uom_id,
            factor: dto.factor,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&UomConversion> for UomConversionResponseDto {
    fn from(entity: &UomConversion) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            from_uom_id: entity.from_uom_id.clone(),
            to_uom_id: entity.to_uom_id.clone(),
            factor: entity.factor.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateUomConversionDto> for UomConversion {
    fn from_create_dto(dto: CreateUomConversionDto) -> backbone_core::ServiceResult<Self> {
        Ok(UomConversion::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateUomConversionDto> for UomConversion {
    fn apply_update(mut self, dto: UpdateUomConversionDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.from_uom_id = dto.from_uom_id;
        self.to_uom_id = dto.to_uom_id;
        self.factor = dto.factor;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to UomConversion here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
