//! Domain specifications
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Combinators (AND/OR/NOT) come from `backbone_core::Specification`.

pub use backbone_core::{Specification, AndSpecification, OrSpecification, NotSpecification};

pub mod attribute_specification;
pub mod attribute_value_specification;
pub mod brand_specification;
pub mod item_specification;
pub mod item_group_specification;
pub mod item_variant_specification;
pub mod uom_specification;
pub mod uom_conversion_specification;

// <<< CUSTOM
// END CUSTOM
