//! Domain policy for ItemGroup aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::ItemGroup;

/// Domain policy for ItemGroup — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<ItemGroup>` in the `// <<< CUSTOM` zone.
pub type ItemGroupDomainPolicy = PermitAllPolicy<ItemGroup>;

// <<< CUSTOM
// END CUSTOM
