//! Domain policies
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod attribute_domain_policy;
pub mod attribute_value_domain_policy;
pub mod brand_domain_policy;
pub mod item_domain_policy;
pub mod item_group_domain_policy;
pub mod item_variant_domain_policy;
pub mod uom_domain_policy;
pub mod uom_conversion_domain_policy;

pub use attribute_domain_policy::AttributeDomainPolicy;
pub use attribute_value_domain_policy::AttributeValueDomainPolicy;
pub use brand_domain_policy::BrandDomainPolicy;
pub use item_domain_policy::ItemDomainPolicy;
pub use item_group_domain_policy::ItemGroupDomainPolicy;
pub use item_variant_domain_policy::ItemVariantDomainPolicy;
pub use uom_domain_policy::UomDomainPolicy;
pub use uom_conversion_domain_policy::UomConversionDomainPolicy;

// <<< CUSTOM
// UoM parent-store tree conversion math (ADR-0023) — hand-authored, user-owned
// (declared in metaphor.codegen.yaml). Declared here inside the CUSTOM block so
// regeneration preserves the wiring.
pub mod uom_tree;
pub use uom_tree::{convert_quantity, ConversionRounding, UomChain, UomChainNode, UomConversionError};
// END CUSTOM
