//! Application service for AttributeValue entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `attribute_value_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateAttributeValueDto, UpdateAttributeValueDto};
use crate::domain::entity::AttributeValue;
use crate::infrastructure::persistence::AttributeValueRepository;

/// Application service for AttributeValue entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `attribute_value_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct AttributeValueServiceCustom {
///     inner: Arc<AttributeValueService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type AttributeValueService = GenericCrudService<
    AttributeValue,
    CreateAttributeValueDto,
    UpdateAttributeValueDto,
    AttributeValueRepository,
>;

// <<< CUSTOM
// END CUSTOM
