//! Application service for ItemVariant entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `item_variant_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateItemVariantDto, UpdateItemVariantDto};
use crate::domain::entity::ItemVariant;
use crate::infrastructure::persistence::ItemVariantRepository;

/// Application service for ItemVariant entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `item_variant_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct ItemVariantServiceCustom {
///     inner: Arc<ItemVariantService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type ItemVariantService = GenericCrudService<
    ItemVariant,
    CreateItemVariantDto,
    UpdateItemVariantDto,
    ItemVariantRepository,
>;

// <<< CUSTOM
// END CUSTOM
