//! Application service for Item entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `item_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateItemDto, UpdateItemDto};
use crate::domain::entity::Item;
use crate::infrastructure::persistence::ItemRepository;

/// Application service for Item entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `item_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct ItemServiceCustom {
///     inner: Arc<ItemService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type ItemService = GenericCrudService<
    Item,
    CreateItemDto,
    UpdateItemDto,
    ItemRepository,
>;

// <<< CUSTOM
// END CUSTOM
