//! Application service for ItemGroup entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `item_group_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateItemGroupDto, UpdateItemGroupDto};
use crate::domain::entity::ItemGroup;
use crate::infrastructure::persistence::ItemGroupRepository;

/// Application service for ItemGroup entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `item_group_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct ItemGroupServiceCustom {
///     inner: Arc<ItemGroupService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type ItemGroupService = GenericCrudService<
    ItemGroup,
    CreateItemGroupDto,
    UpdateItemGroupDto,
    ItemGroupRepository,
>;

// <<< CUSTOM
// END CUSTOM
