//! Application services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

pub mod attribute_service;
pub mod attribute_value_service;
pub mod brand_service;
pub mod item_service;
pub mod item_group_service;
pub mod item_variant_service;
pub mod uom_service;
pub mod uom_conversion_service;

// <<< CUSTOM
pub mod catalog_write_service;
// END CUSTOM

pub use attribute_service::AttributeService;
pub use attribute_value_service::AttributeValueService;
pub use brand_service::BrandService;
pub use item_service::ItemService;
pub use item_group_service::ItemGroupService;
pub use item_variant_service::ItemVariantService;
pub use uom_service::UomService;
pub use uom_conversion_service::UomConversionService;
// <<< CUSTOM
pub use catalog_write_service::{
    CatalogWriteError, CatalogWriteService, NewAttribute, NewAttributeValue, NewBrand, NewItem,
    NewItemGroup, NewItemVariant, NewUom, NewUomConversion,
};
// END CUSTOM