//! Application service for Uom entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `uom_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateUomDto, UpdateUomDto};
use crate::domain::entity::Uom;
use crate::infrastructure::persistence::UomRepository;

/// Application service for Uom entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `uom_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct UomServiceCustom {
///     inner: Arc<UomService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type UomService = GenericCrudService<
    Uom,
    CreateUomDto,
    UpdateUomDto,
    UomRepository,
>;

// <<< CUSTOM
// END CUSTOM
