-- AttributeValue Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the catalog.attribute_values table.
-- Customize this file to add your initial data.

-- INSERT INTO catalog.attribute_values (
--     id,
--     attribute_id,
--     code,
--     label,
--     label_en,
--     swatch_hex,
--     icon,
--     sort_order,
--     status,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert reference data
-- Uncomment and modify the following:

-- INSERT INTO catalog.attribute_values (id, code, name, is_active, created_at, updated_at) VALUES
--     (gen_random_uuid(), 'SAMPLE1', 'Sample 1', true, NOW(), NOW()),
--     (gen_random_uuid(), 'SAMPLE2', 'Sample 2', true, NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

