-- SEED: none
--
-- Product attributes describe a company's own catalogue. Size, colour and material
-- look universal until the first tenant sells something measured differently.
--
-- The tenancy descriptor anchors this table on a company or branch node, which
-- is the same statement in schema form: there is no tenant-independent row to
-- seed, and a seed run has no company to anchor one to.
