-- ItemVariant Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the catalog.item_variants table.
-- Customize this file to add your initial data.

-- INSERT INTO catalog.item_variants (
--     id,
--     item_id,
--     sku,
--     variant_label,
--     options,
--     barcode,
--     is_default,
--     weight_per_unit,
--     status,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO catalog.item_variants (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

