-- Item Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the catalog.items table.
-- Customize this file to add your initial data.

-- INSERT INTO catalog.items (
--     id,
--     item_code,
--     name,
--     description,
--     barcode,
--     brand_id,
--     item_group_id,
--     default_uom_id,
--     item_type,
--     is_sales_item,
--     is_purchase_item,
--     is_stock_item,
--     has_variants,
--     hsn_code,
--     sni,
--     is_taxable,
--     weight_per_unit,
--     shelf_life_days,
--     tags,
--     data,
--     status,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert reference data
-- Uncomment and modify the following:

-- INSERT INTO catalog.items (id, code, name, is_active, created_at, updated_at) VALUES
--     (gen_random_uuid(), 'SAMPLE1', 'Sample 1', true, NOW(), NOW()),
--     (gen_random_uuid(), 'SAMPLE2', 'Sample 2', true, NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

