-- UomConversion Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the catalog.uom_conversions table.
-- Customize this file to add your initial data.

-- INSERT INTO catalog.uom_conversions (
--     id,
--     from_uom_id,
--     to_uom_id,
--     factor,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO catalog.uom_conversions (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

