-- Migration: Create attribute_values table
-- Generated by metaphor-schema

-- Create catalog_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'catalog_status') THEN
        CREATE TYPE catalog_status AS ENUM ('active', 'inactive', 'discontinued');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS catalog;

CREATE TABLE IF NOT EXISTS catalog.attribute_values (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    attribute_id UUID NOT NULL,
    code TEXT NOT NULL,
    label TEXT NOT NULL,
    label_en TEXT,
    swatch_hex TEXT,
    icon TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    status catalog_status NOT NULL DEFAULT 'active',
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_attribute_values_attribute_id_code ON catalog.attribute_values (attribute_id, code) WHERE (metadata->>'deleted_at') IS NULL;

CREATE INDEX IF NOT EXISTS idx_attribute_values_attribute_id_sort_order ON catalog.attribute_values (attribute_id, sort_order);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_attribute_values_metadata_gin ON catalog.attribute_values USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_attribute_values_metadata_deleted_at ON catalog.attribute_values ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_attribute_values_metadata_created_at ON catalog.attribute_values ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_attribute_values_metadata_updated_at ON catalog.attribute_values ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION catalog.attribute_values_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS attribute_values_insert_audit ON catalog.attribute_values;
CREATE TRIGGER attribute_values_insert_audit BEFORE INSERT ON catalog.attribute_values
    FOR EACH ROW EXECUTE FUNCTION catalog.attribute_values_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS attribute_values_update_audit ON catalog.attribute_values;
CREATE TRIGGER attribute_values_update_audit BEFORE UPDATE ON catalog.attribute_values
    FOR EACH ROW EXECUTE FUNCTION catalog.attribute_values_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE catalog.attribute_values ADD CONSTRAINT fk_attribute_values_attribute_id FOREIGN KEY (attribute_id) REFERENCES catalog.attributes (id);
