-- Migration: Create item_groups table
-- Generated by metaphor-schema

-- Create catalog_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'catalog_status') THEN
        CREATE TYPE catalog_status AS ENUM ('active', 'inactive', 'discontinued');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS catalog;

CREATE TABLE IF NOT EXISTS catalog.item_groups (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    parent_id UUID,
    is_group BOOLEAN NOT NULL DEFAULT FALSE,
    level INTEGER NOT NULL DEFAULT 0,
    sort_order INTEGER NOT NULL DEFAULT 0,
    status catalog_status NOT NULL DEFAULT 'active',
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_item_groups_code ON catalog.item_groups (code) WHERE (metadata->>'deleted_at') IS NULL;

CREATE INDEX IF NOT EXISTS idx_item_groups_parent_id_sort_order ON catalog.item_groups (parent_id, sort_order);

CREATE INDEX IF NOT EXISTS idx_item_groups_status ON catalog.item_groups (status);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_item_groups_metadata_gin ON catalog.item_groups USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_item_groups_metadata_deleted_at ON catalog.item_groups ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_item_groups_metadata_created_at ON catalog.item_groups ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_item_groups_metadata_updated_at ON catalog.item_groups ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION catalog.item_groups_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS item_groups_insert_audit ON catalog.item_groups;
CREATE TRIGGER item_groups_insert_audit BEFORE INSERT ON catalog.item_groups
    FOR EACH ROW EXECUTE FUNCTION catalog.item_groups_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS item_groups_update_audit ON catalog.item_groups;
CREATE TRIGGER item_groups_update_audit BEFORE UPDATE ON catalog.item_groups
    FOR EACH ROW EXECUTE FUNCTION catalog.item_groups_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE catalog.item_groups ADD CONSTRAINT fk_item_groups_parent_id FOREIGN KEY (parent_id) REFERENCES catalog.item_groups (id);
