-- Migration: Create items table
-- Generated by metaphor-schema

-- Create item_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'item_type') THEN
        CREATE TYPE item_type AS ENUM ('physical_good', 'digital_good', 'service', 'subscription', 'bundle', 'gift_card', 'rental');
    END IF;
END
$$;

-- Create catalog_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'catalog_status') THEN
        CREATE TYPE catalog_status AS ENUM ('active', 'inactive', 'discontinued');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS catalog;

CREATE TABLE IF NOT EXISTS catalog.items (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    item_code TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    barcode TEXT,
    brand_id UUID,
    item_group_id UUID NOT NULL,
    default_uom_id UUID NOT NULL,
    item_type item_type NOT NULL DEFAULT 'physical_good',
    is_sales_item BOOLEAN NOT NULL DEFAULT TRUE,
    is_purchase_item BOOLEAN NOT NULL DEFAULT TRUE,
    is_stock_item BOOLEAN NOT NULL DEFAULT TRUE,
    has_variants BOOLEAN NOT NULL DEFAULT FALSE,
    hsn_code TEXT,
    sni TEXT,
    is_taxable BOOLEAN NOT NULL DEFAULT TRUE,
    weight_per_unit NUMERIC(18, 4),
    shelf_life_days INTEGER CHECK (shelf_life_days >= 0),
    tags JSONB NOT NULL DEFAULT '[]'::jsonb,
    data JSONB NOT NULL DEFAULT '{}'::jsonb,
    status catalog_status NOT NULL DEFAULT 'active',
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_items_item_code ON catalog.items (item_code) WHERE (metadata->>'deleted_at') IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_items_barcode ON catalog.items (barcode) WHERE barcode IS NOT NULL AND (metadata->>'deleted_at') IS NULL;

CREATE INDEX IF NOT EXISTS idx_items_item_group_id_status ON catalog.items (item_group_id, status);

CREATE INDEX IF NOT EXISTS idx_items_item_type ON catalog.items (item_type);

CREATE INDEX IF NOT EXISTS idx_items_status ON catalog.items (status);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_items_metadata_gin ON catalog.items USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_items_metadata_deleted_at ON catalog.items ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_items_metadata_created_at ON catalog.items ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_items_metadata_updated_at ON catalog.items ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION catalog.items_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS items_insert_audit ON catalog.items;
CREATE TRIGGER items_insert_audit BEFORE INSERT ON catalog.items
    FOR EACH ROW EXECUTE FUNCTION catalog.items_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS items_update_audit ON catalog.items;
CREATE TRIGGER items_update_audit BEFORE UPDATE ON catalog.items
    FOR EACH ROW EXECUTE FUNCTION catalog.items_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE catalog.items ADD CONSTRAINT fk_items_item_group_id FOREIGN KEY (item_group_id) REFERENCES catalog.item_groups (id);
ALTER TABLE catalog.items ADD CONSTRAINT fk_items_brand_id FOREIGN KEY (brand_id) REFERENCES catalog.brands (id);
ALTER TABLE catalog.items ADD CONSTRAINT fk_items_default_uom_id FOREIGN KEY (default_uom_id) REFERENCES catalog.uoms (id);
