-- Migration: Create uom_conversions table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS catalog;

CREATE TABLE IF NOT EXISTS catalog.uom_conversions (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    from_uom_id UUID NOT NULL,
    to_uom_id UUID NOT NULL,
    factor NUMERIC NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_uom_conversions_from_uom_id_to_uom_id ON catalog.uom_conversions (from_uom_id, to_uom_id) WHERE (metadata->>'deleted_at') IS NULL;

CREATE INDEX IF NOT EXISTS idx_uom_conversions_from_uom_id ON catalog.uom_conversions (from_uom_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_uom_conversions_metadata_gin ON catalog.uom_conversions USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_uom_conversions_metadata_deleted_at ON catalog.uom_conversions ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_uom_conversions_metadata_created_at ON catalog.uom_conversions ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_uom_conversions_metadata_updated_at ON catalog.uom_conversions ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION catalog.uom_conversions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS uom_conversions_insert_audit ON catalog.uom_conversions;
CREATE TRIGGER uom_conversions_insert_audit BEFORE INSERT ON catalog.uom_conversions
    FOR EACH ROW EXECUTE FUNCTION catalog.uom_conversions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS uom_conversions_update_audit ON catalog.uom_conversions;
CREATE TRIGGER uom_conversions_update_audit BEFORE UPDATE ON catalog.uom_conversions
    FOR EACH ROW EXECUTE FUNCTION catalog.uom_conversions_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE catalog.uom_conversions ADD CONSTRAINT fk_uom_conversions_from_uom_id FOREIGN KEY (from_uom_id) REFERENCES catalog.uoms (id);
ALTER TABLE catalog.uom_conversions ADD CONSTRAINT fk_uom_conversions_to_uom_id FOREIGN KEY (to_uom_id) REFERENCES catalog.uoms (id);
