-- Audit Triggers Migration for catalog module
-- Generated by metaphor-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: Attribute (catalog.attributes)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION catalog.attributes_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS attributes_insert_audit ON catalog.attributes;
CREATE TRIGGER attributes_insert_audit BEFORE INSERT ON catalog.attributes
    FOR EACH ROW EXECUTE FUNCTION catalog.attributes_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS attributes_update_audit ON catalog.attributes;
CREATE TRIGGER attributes_update_audit BEFORE UPDATE ON catalog.attributes
    FOR EACH ROW EXECUTE FUNCTION catalog.attributes_audit_timestamp();

-- ==============================================================================
-- Table: AttributeValue (catalog.attribute_values)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION catalog.attribute_values_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS attribute_values_insert_audit ON catalog.attribute_values;
CREATE TRIGGER attribute_values_insert_audit BEFORE INSERT ON catalog.attribute_values
    FOR EACH ROW EXECUTE FUNCTION catalog.attribute_values_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS attribute_values_update_audit ON catalog.attribute_values;
CREATE TRIGGER attribute_values_update_audit BEFORE UPDATE ON catalog.attribute_values
    FOR EACH ROW EXECUTE FUNCTION catalog.attribute_values_audit_timestamp();

-- ==============================================================================
-- Table: Brand (catalog.brands)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION catalog.brands_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS brands_insert_audit ON catalog.brands;
CREATE TRIGGER brands_insert_audit BEFORE INSERT ON catalog.brands
    FOR EACH ROW EXECUTE FUNCTION catalog.brands_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS brands_update_audit ON catalog.brands;
CREATE TRIGGER brands_update_audit BEFORE UPDATE ON catalog.brands
    FOR EACH ROW EXECUTE FUNCTION catalog.brands_audit_timestamp();

-- ==============================================================================
-- Table: Item (catalog.items)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION catalog.items_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS items_insert_audit ON catalog.items;
CREATE TRIGGER items_insert_audit BEFORE INSERT ON catalog.items
    FOR EACH ROW EXECUTE FUNCTION catalog.items_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS items_update_audit ON catalog.items;
CREATE TRIGGER items_update_audit BEFORE UPDATE ON catalog.items
    FOR EACH ROW EXECUTE FUNCTION catalog.items_audit_timestamp();

-- ==============================================================================
-- Table: ItemGroup (catalog.item_groups)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION catalog.item_groups_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS item_groups_insert_audit ON catalog.item_groups;
CREATE TRIGGER item_groups_insert_audit BEFORE INSERT ON catalog.item_groups
    FOR EACH ROW EXECUTE FUNCTION catalog.item_groups_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS item_groups_update_audit ON catalog.item_groups;
CREATE TRIGGER item_groups_update_audit BEFORE UPDATE ON catalog.item_groups
    FOR EACH ROW EXECUTE FUNCTION catalog.item_groups_audit_timestamp();

-- ==============================================================================
-- Table: ItemVariant (catalog.item_variants)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION catalog.item_variants_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS item_variants_insert_audit ON catalog.item_variants;
CREATE TRIGGER item_variants_insert_audit BEFORE INSERT ON catalog.item_variants
    FOR EACH ROW EXECUTE FUNCTION catalog.item_variants_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS item_variants_update_audit ON catalog.item_variants;
CREATE TRIGGER item_variants_update_audit BEFORE UPDATE ON catalog.item_variants
    FOR EACH ROW EXECUTE FUNCTION catalog.item_variants_audit_timestamp();

-- ==============================================================================
-- Table: Uom (catalog.uoms)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION catalog.uoms_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS uoms_insert_audit ON catalog.uoms;
CREATE TRIGGER uoms_insert_audit BEFORE INSERT ON catalog.uoms
    FOR EACH ROW EXECUTE FUNCTION catalog.uoms_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS uoms_update_audit ON catalog.uoms;
CREATE TRIGGER uoms_update_audit BEFORE UPDATE ON catalog.uoms
    FOR EACH ROW EXECUTE FUNCTION catalog.uoms_audit_timestamp();

-- ==============================================================================
-- Table: UomConversion (catalog.uom_conversions)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION catalog.uom_conversions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS uom_conversions_insert_audit ON catalog.uom_conversions;
CREATE TRIGGER uom_conversions_insert_audit BEFORE INSERT ON catalog.uom_conversions
    FOR EACH ROW EXECUTE FUNCTION catalog.uom_conversions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS uom_conversions_update_audit ON catalog.uom_conversions;
CREATE TRIGGER uom_conversions_update_audit BEFORE UPDATE ON catalog.uom_conversions
    FOR EACH ROW EXECUTE FUNCTION catalog.uom_conversions_audit_timestamp();

