-- Migration: Create attributes table
-- Generated by metaphor-schema

-- Create attribute_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'attribute_type') THEN
        CREATE TYPE attribute_type AS ENUM ('color', 'size', 'material', 'style', 'capacity', 'other');
    END IF;
END
$$;

-- Create catalog_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'catalog_status') THEN
        CREATE TYPE catalog_status AS ENUM ('active', 'inactive', 'discontinued');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS catalog;

CREATE TABLE IF NOT EXISTS catalog.attributes (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    attribute_type attribute_type NOT NULL DEFAULT 'other',
    status catalog_status NOT NULL DEFAULT 'active',
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_attributes_code ON catalog.attributes (code) WHERE (metadata->>'deleted_at') IS NULL;

CREATE INDEX IF NOT EXISTS idx_attributes_status ON catalog.attributes (status);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_attributes_metadata_gin ON catalog.attributes USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_attributes_metadata_deleted_at ON catalog.attributes ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_attributes_metadata_created_at ON catalog.attributes ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_attributes_metadata_updated_at ON catalog.attributes ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION catalog.attributes_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS attributes_insert_audit ON catalog.attributes;
CREATE TRIGGER attributes_insert_audit BEFORE INSERT ON catalog.attributes
    FOR EACH ROW EXECUTE FUNCTION catalog.attributes_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS attributes_update_audit ON catalog.attributes;
CREATE TRIGGER attributes_update_audit BEFORE UPDATE ON catalog.attributes
    FOR EACH ROW EXECUTE FUNCTION catalog.attributes_audit_timestamp();
