-- Enum types for catalog module
-- Generated by metaphor-schema

-- Create attribute_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'attribute_type') THEN
        CREATE TYPE attribute_type AS ENUM ('color', 'size', 'material', 'style', 'capacity', 'other');
    END IF;
END
$$;

-- Create item_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'item_type') THEN
        CREATE TYPE item_type AS ENUM ('physical_good', 'digital_good', 'service', 'subscription', 'bundle', 'gift_card', 'rental');
    END IF;
END
$$;

-- Create catalog_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'catalog_status') THEN
        CREATE TYPE catalog_status AS ENUM ('active', 'inactive', 'discontinued');
    END IF;
END
$$;

-- Create uom_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'uom_type') THEN
        CREATE TYPE uom_type AS ENUM ('count', 'weight', 'volume', 'length', 'area', 'time', 'other');
    END IF;
END
$$;

