-- Migration: Create item_variants table
-- Generated by metaphor-schema

-- Create catalog_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'catalog_status') THEN
        CREATE TYPE catalog_status AS ENUM ('active', 'inactive', 'discontinued');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS catalog;

CREATE TABLE IF NOT EXISTS catalog.item_variants (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    item_id UUID NOT NULL,
    sku TEXT NOT NULL,
    variant_label TEXT NOT NULL,
    options JSONB NOT NULL DEFAULT '{}'::jsonb,
    barcode TEXT,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    weight_per_unit NUMERIC,
    status catalog_status NOT NULL DEFAULT 'active',
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_item_variants_sku ON catalog.item_variants (sku) WHERE (metadata->>'deleted_at') IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_item_variants_barcode ON catalog.item_variants (barcode) WHERE barcode IS NOT NULL AND (metadata->>'deleted_at') IS NULL;

CREATE INDEX IF NOT EXISTS idx_item_variants_item_id_is_default ON catalog.item_variants (item_id, is_default);

CREATE INDEX IF NOT EXISTS idx_item_variants_item_id_status ON catalog.item_variants (item_id, status);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_item_variants_metadata_gin ON catalog.item_variants USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_item_variants_metadata_deleted_at ON catalog.item_variants ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_item_variants_metadata_created_at ON catalog.item_variants ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_item_variants_metadata_updated_at ON catalog.item_variants ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION catalog.item_variants_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS item_variants_insert_audit ON catalog.item_variants;
CREATE TRIGGER item_variants_insert_audit BEFORE INSERT ON catalog.item_variants
    FOR EACH ROW EXECUTE FUNCTION catalog.item_variants_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS item_variants_update_audit ON catalog.item_variants;
CREATE TRIGGER item_variants_update_audit BEFORE UPDATE ON catalog.item_variants
    FOR EACH ROW EXECUTE FUNCTION catalog.item_variants_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE catalog.item_variants ADD CONSTRAINT fk_item_variants_item_id FOREIGN KEY (item_id) REFERENCES catalog.items (id);
