//! Event handler trait for Attribute events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::AttributeEvent;

/// Event handler for Attribute events.
/// Implement this trait to react to Attribute lifecycle events.
pub trait AttributeEventHandler: EventHandler<AttributeEvent> {}
