//! Domain events for AttributeValue entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::AttributeValue;

/// Domain events for AttributeValue — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<AttributeValue>)` variant.
pub type AttributeValueEvent = CrudEvent<AttributeValue>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for AttributeValue events.
pub type AttributeValueEventPublisher = Arc<dyn CrudEventPublisher<AttributeValue> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopAttributeValueEventPublisher = NoOpCrudEventPublisher<AttributeValue>;
