//! Domain events for Attribute entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Attribute;

/// Domain events for Attribute — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Attribute>)` variant.
pub type AttributeEvent = CrudEvent<Attribute>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Attribute events.
pub type AttributeEventPublisher = Arc<dyn CrudEventPublisher<Attribute> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopAttributeEventPublisher = NoOpCrudEventPublisher<Attribute>;
