//! Event handler trait for AttributeValue events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::AttributeValueEvent;

/// Event handler for AttributeValue events.
/// Implement this trait to react to AttributeValue lifecycle events.
pub trait AttributeValueEventHandler: EventHandler<AttributeValueEvent> {}
