//! Domain events for Brand entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Brand;

/// Domain events for Brand — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Brand>)` variant.
pub type BrandEvent = CrudEvent<Brand>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Brand events.
pub type BrandEventPublisher = Arc<dyn CrudEventPublisher<Brand> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopBrandEventPublisher = NoOpCrudEventPublisher<Brand>;
