//! Event handler trait for Brand events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::BrandEvent;

/// Event handler for Brand events.
/// Implement this trait to react to Brand lifecycle events.
pub trait BrandEventHandler: EventHandler<BrandEvent> {}
