//! Domain events for Item entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Item;

/// Domain events for Item — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Item>)` variant.
pub type ItemEvent = CrudEvent<Item>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Item events.
pub type ItemEventPublisher = Arc<dyn CrudEventPublisher<Item> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopItemEventPublisher = NoOpCrudEventPublisher<Item>;
