//! Event handler trait for ItemGroup events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::ItemGroupEvent;

/// Event handler for ItemGroup events.
/// Implement this trait to react to ItemGroup lifecycle events.
pub trait ItemGroupEventHandler: EventHandler<ItemGroupEvent> {}
