//! Event handler trait for Item events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::ItemEvent;

/// Event handler for Item events.
/// Implement this trait to react to Item lifecycle events.
pub trait ItemEventHandler: EventHandler<ItemEvent> {}
