//! Domain events for ItemVariant entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::ItemVariant;

/// Domain events for ItemVariant — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<ItemVariant>)` variant.
pub type ItemVariantEvent = CrudEvent<ItemVariant>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for ItemVariant events.
pub type ItemVariantEventPublisher = Arc<dyn CrudEventPublisher<ItemVariant> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopItemVariantEventPublisher = NoOpCrudEventPublisher<ItemVariant>;
