//! Event handler trait for ItemVariant events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::ItemVariantEvent;

/// Event handler for ItemVariant events.
/// Implement this trait to react to ItemVariant lifecycle events.
pub trait ItemVariantEventHandler: EventHandler<ItemVariantEvent> {}
