//! Domain events for ItemGroup entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::ItemGroup;

/// Domain events for ItemGroup — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<ItemGroup>)` variant.
pub type ItemGroupEvent = CrudEvent<ItemGroup>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for ItemGroup events.
pub type ItemGroupEventPublisher = Arc<dyn CrudEventPublisher<ItemGroup> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopItemGroupEventPublisher = NoOpCrudEventPublisher<ItemGroup>;
