//! Event handler trait for Uom events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::UomEvent;

/// Event handler for Uom events.
/// Implement this trait to react to Uom lifecycle events.
pub trait UomEventHandler: EventHandler<UomEvent> {}
