//! Domain events for UomConversion entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::UomConversion;

/// Domain events for UomConversion — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<UomConversion>)` variant.
pub type UomConversionEvent = CrudEvent<UomConversion>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for UomConversion events.
pub type UomConversionEventPublisher = Arc<dyn CrudEventPublisher<UomConversion> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopUomConversionEventPublisher = NoOpCrudEventPublisher<UomConversion>;
