//! Event handler trait for UomConversion events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::UomConversionEvent;

/// Event handler for UomConversion events.
/// Implement this trait to react to UomConversion lifecycle events.
pub trait UomConversionEventHandler: EventHandler<UomConversionEvent> {}
