//! Domain events for Uom entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Uom;

/// Domain events for Uom — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Uom>)` variant.
pub type UomEvent = CrudEvent<Uom>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Uom events.
pub type UomEventPublisher = Arc<dyn CrudEventPublisher<Uom> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopUomEventPublisher = NoOpCrudEventPublisher<Uom>;
