//! Event subscriber type aliases for Catalog module
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::GenericEventSubscriber;

use crate::domain::event::AttributeEvent;
use crate::domain::event::AttributeValueEvent;
use crate::domain::event::BrandEvent;
use crate::domain::event::ItemEvent;
use crate::domain::event::ItemGroupEvent;
use crate::domain::event::ItemVariantEvent;
use crate::domain::event::UomEvent;
use crate::domain::event::UomConversionEvent;

/// Subscriber for Attribute events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type AttributeEventSubscriber = GenericEventSubscriber<AttributeEvent>;

/// Subscriber for AttributeValue events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type AttributeValueEventSubscriber = GenericEventSubscriber<AttributeValueEvent>;

/// Subscriber for Brand events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type BrandEventSubscriber = GenericEventSubscriber<BrandEvent>;

/// Subscriber for Item events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type ItemEventSubscriber = GenericEventSubscriber<ItemEvent>;

/// Subscriber for ItemGroup events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type ItemGroupEventSubscriber = GenericEventSubscriber<ItemGroupEvent>;

/// Subscriber for ItemVariant events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type ItemVariantEventSubscriber = GenericEventSubscriber<ItemVariantEvent>;

/// Subscriber for Uom events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type UomEventSubscriber = GenericEventSubscriber<UomEvent>;

/// Subscriber for UomConversion events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type UomConversionEventSubscriber = GenericEventSubscriber<UomConversionEvent>;

// <<< CUSTOM
// END CUSTOM
