//! Catalog Event Subscriptions
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Cross-module event subscriptions. Each entity subscriber is a type alias
//! over `GenericEventSubscriber` from backbone-messaging.

pub mod handlers;
pub mod registry;

pub use handlers::*;
pub use registry::SubscriptionRegistry;

pub use handlers::AttributeEventSubscriber;
pub use handlers::AttributeValueEventSubscriber;
pub use handlers::BrandEventSubscriber;
pub use handlers::ItemEventSubscriber;
pub use handlers::ItemGroupEventSubscriber;
pub use handlers::ItemVariantEventSubscriber;
pub use handlers::UomEventSubscriber;
pub use handlers::UomConversionEventSubscriber;
