//! AttributeValue seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial AttributeValue data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// ATTRIBUTEVALUE SEEDER
// ============================================================================

/// Seeder for attribute_value
pub struct SeedAttributeValueSeeder;

impl SeedAttributeValueSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedAttributeValueSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedAttributeValueSeeder {
    fn name(&self) -> &'static str {
        "SeedAttributeValueSeeder"
    }

    fn order(&self) -> i32 {
        2
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if catalog.attribute_values table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM catalog.attribute_values")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/attribute_value_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM catalog.attribute_values")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

