//! Brand seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial Brand data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// BRAND SEEDER
// ============================================================================

/// Seeder for brand
pub struct SeedBrandSeeder;

impl SeedBrandSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedBrandSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedBrandSeeder {
    fn name(&self) -> &'static str {
        "SeedBrandSeeder"
    }

    fn order(&self) -> i32 {
        3
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if catalog.brands table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM catalog.brands")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/brand_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM catalog.brands")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

