//! ItemGroup seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial ItemGroup data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// ITEMGROUP SEEDER
// ============================================================================

/// Seeder for item_group
pub struct SeedItemGroupSeeder;

impl SeedItemGroupSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedItemGroupSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedItemGroupSeeder {
    fn name(&self) -> &'static str {
        "SeedItemGroupSeeder"
    }

    fn order(&self) -> i32 {
        8
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if catalog.item_groups table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM catalog.item_groups")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/item_group_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM catalog.item_groups")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

