//! Database seeders for the catalog module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides seed data for initial database setup.
//! Seeders can be run via the seeder binary or CLI.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

mod attribute_seeder;
mod attribute_value_seeder;
mod brand_seeder;
mod item_seeder;
mod item_group_seeder;
mod item_variant_seeder;
mod uom_seeder;
mod uom_conversion_seeder;

pub use attribute_seeder::SeedAttributeSeeder;
pub use attribute_value_seeder::SeedAttributeValueSeeder;
pub use brand_seeder::SeedBrandSeeder;
pub use item_seeder::SeedItemSeeder;
pub use item_group_seeder::SeedItemGroupSeeder;
pub use item_variant_seeder::SeedItemVariantSeeder;
pub use uom_seeder::SeedUomSeeder;
pub use uom_conversion_seeder::SeedUomConversionSeeder;

// ============================================================================
// SEEDER TRAIT
// ============================================================================

/// Trait for database seeders
#[async_trait]
pub trait Seeder {
    /// Get the name of this seeder
    fn name(&self) -> &'static str;

    /// Get the order in which this seeder should run
    fn order(&self) -> i32;

    /// Check if this seeder should run (e.g., check if data already exists)
    async fn should_run(&self, pool: &PgPool) -> Result<bool>;

    /// Run the seeder
    async fn run(&self, pool: &PgPool) -> Result<()>;

    /// Rollback the seeder (optional)
    async fn rollback(&self, _pool: &PgPool) -> Result<()> {
        Ok(())
    }
}

// ============================================================================
// SEEDER TYPE
// ============================================================================

/// Type of seeder
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SeederType {
    /// Reference data (required for application to function)
    Reference,
    /// Initial production data
    Production,
    /// Development/testing data
    Development,
    /// Test data (for automated tests)
    Test,
// <<< CUSTOM SEEDERS START >>>
// Add custom seeders here.
}

// ============================================================================
// CUSTOM SEEDERS
// ============================================================================

// <<< CUSTOM SEEDERS START >>>
// Add custom seeders here
// <<< CUSTOM SEEDERS END >>>
