//! Repository trait for Attribute aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Attribute aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Attribute, AttributeType, CatalogStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct AttributePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl AttributePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct AttributePaginatedResult {
    pub data: Vec<Attribute>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct AttributeFilter {
    pub company_id: Option<Uuid>,
    pub code: Option<String>,
    pub name: Option<String>,
    pub attribute_type: Option<AttributeType>,
    pub status: Option<CatalogStatus>,
}

impl AttributeFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.code.is_some() || self.name.is_some() || self.attribute_type.is_some() || self.status.is_some()
    }
}

/// Repository trait for Attribute aggregate
///
/// This trait defines the persistence contract for Attribute entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait AttributeRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new attribute entity
    async fn save(&self, entity: &Attribute) -> Result<Attribute>;

    /// Find attribute by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Attribute>>;

    /// Find all attribute entities
    async fn find_all(&self) -> Result<Vec<Attribute>>;

    /// Update attribute by ID
    async fn update(&self, id: &str, entity: &Attribute) -> Result<Option<Attribute>>;

    /// Delete attribute by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List attribute with pagination
    async fn list(&self, params: AttributePaginationParams) -> Result<AttributePaginatedResult>;

    /// List attribute with pagination and filters
    async fn list_with_filters(&self, params: AttributePaginationParams, filters: AttributeFilter) -> Result<AttributePaginatedResult>;

    /// Count all attribute entities
    async fn count(&self) -> Result<u64>;

    /// Count attribute entities matching filters
    async fn count_with_filters(&self, filters: AttributeFilter) -> Result<u64>;

    /// Check if attribute exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete attribute by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted attribute by ID
    async fn restore(&self, id: &str) -> Result<Option<Attribute>>;

    /// List soft-deleted attribute entities
    async fn list_deleted(&self, params: AttributePaginationParams) -> Result<AttributePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save attribute entities
    async fn bulk_save(&self, entities: &[Attribute]) -> Result<Vec<Attribute>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
