//! Repository trait for Brand aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Brand aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Brand, CatalogStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct BrandPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl BrandPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct BrandPaginatedResult {
    pub data: Vec<Brand>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct BrandFilter {
    pub company_id: Option<Uuid>,
    pub code: Option<String>,
    pub name: Option<String>,
    pub short_description: Option<String>,
    pub description: Option<String>,
    pub logo_url: Option<String>,
    pub status: Option<CatalogStatus>,
}

impl BrandFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.code.is_some() || self.name.is_some() || self.short_description.is_some() || self.description.is_some() || self.logo_url.is_some() || self.status.is_some()
    }
}

/// Repository trait for Brand aggregate
///
/// This trait defines the persistence contract for Brand entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait BrandRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new brand entity
    async fn save(&self, entity: &Brand) -> Result<Brand>;

    /// Find brand by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Brand>>;

    /// Find all brand entities
    async fn find_all(&self) -> Result<Vec<Brand>>;

    /// Update brand by ID
    async fn update(&self, id: &str, entity: &Brand) -> Result<Option<Brand>>;

    /// Delete brand by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List brand with pagination
    async fn list(&self, params: BrandPaginationParams) -> Result<BrandPaginatedResult>;

    /// List brand with pagination and filters
    async fn list_with_filters(&self, params: BrandPaginationParams, filters: BrandFilter) -> Result<BrandPaginatedResult>;

    /// Count all brand entities
    async fn count(&self) -> Result<u64>;

    /// Count brand entities matching filters
    async fn count_with_filters(&self, filters: BrandFilter) -> Result<u64>;

    /// Check if brand exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete brand by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted brand by ID
    async fn restore(&self, id: &str) -> Result<Option<Brand>>;

    /// List soft-deleted brand entities
    async fn list_deleted(&self, params: BrandPaginationParams) -> Result<BrandPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save brand entities
    async fn bulk_save(&self, entities: &[Brand]) -> Result<Vec<Brand>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
