//! Repository trait for Item aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Item aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Item, CatalogStatus, ItemType};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ItemPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl ItemPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct ItemPaginatedResult {
    pub data: Vec<Item>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ItemFilter {
    pub item_code: Option<String>,
    pub name: Option<String>,
    pub description: Option<String>,
    pub barcode: Option<String>,
    pub brand_id: Option<Uuid>,
    pub item_group_id: Option<Uuid>,
    pub default_uom_id: Option<Uuid>,
    pub item_type: Option<ItemType>,
    pub is_sales_item: Option<bool>,
    pub is_purchase_item: Option<bool>,
    pub is_stock_item: Option<bool>,
    pub has_variants: Option<bool>,
    pub hsn_code: Option<String>,
    pub sni: Option<String>,
    pub is_taxable: Option<bool>,
    pub status: Option<CatalogStatus>,
}

impl ItemFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.item_code.is_some() || self.name.is_some() || self.description.is_some() || self.barcode.is_some() || self.brand_id.is_some() || self.item_group_id.is_some() || self.default_uom_id.is_some() || self.item_type.is_some() || self.is_sales_item.is_some() || self.is_purchase_item.is_some() || self.is_stock_item.is_some() || self.has_variants.is_some() || self.hsn_code.is_some() || self.sni.is_some() || self.is_taxable.is_some() || self.status.is_some()
    }
}

/// Repository trait for Item aggregate
///
/// This trait defines the persistence contract for Item entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait ItemRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new item entity
    async fn save(&self, entity: &Item) -> Result<Item>;

    /// Find item by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Item>>;

    /// Find all item entities
    async fn find_all(&self) -> Result<Vec<Item>>;

    /// Update item by ID
    async fn update(&self, id: &str, entity: &Item) -> Result<Option<Item>>;

    /// Delete item by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List item with pagination
    async fn list(&self, params: ItemPaginationParams) -> Result<ItemPaginatedResult>;

    /// List item with pagination and filters
    async fn list_with_filters(&self, params: ItemPaginationParams, filters: ItemFilter) -> Result<ItemPaginatedResult>;

    /// Count all item entities
    async fn count(&self) -> Result<u64>;

    /// Count item entities matching filters
    async fn count_with_filters(&self, filters: ItemFilter) -> Result<u64>;

    /// Check if item exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete item by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted item by ID
    async fn restore(&self, id: &str) -> Result<Option<Item>>;

    /// List soft-deleted item entities
    async fn list_deleted(&self, params: ItemPaginationParams) -> Result<ItemPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save item entities
    async fn bulk_save(&self, entities: &[Item]) -> Result<Vec<Item>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
