//! Repository trait for ItemVariant aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the ItemVariant aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{ItemVariant, CatalogStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ItemVariantPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl ItemVariantPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct ItemVariantPaginatedResult {
    pub data: Vec<ItemVariant>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ItemVariantFilter {
    pub company_id: Option<Uuid>,
    pub item_id: Option<Uuid>,
    pub sku: Option<String>,
    pub variant_label: Option<String>,
    pub barcode: Option<String>,
    pub is_default: Option<bool>,
    pub status: Option<CatalogStatus>,
}

impl ItemVariantFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.item_id.is_some() || self.sku.is_some() || self.variant_label.is_some() || self.barcode.is_some() || self.is_default.is_some() || self.status.is_some()
    }
}

/// Repository trait for ItemVariant aggregate
///
/// This trait defines the persistence contract for ItemVariant entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait ItemVariantRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new item_variant entity
    async fn save(&self, entity: &ItemVariant) -> Result<ItemVariant>;

    /// Find item_variant by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<ItemVariant>>;

    /// Find all item_variant entities
    async fn find_all(&self) -> Result<Vec<ItemVariant>>;

    /// Update item_variant by ID
    async fn update(&self, id: &str, entity: &ItemVariant) -> Result<Option<ItemVariant>>;

    /// Delete item_variant by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List item_variant with pagination
    async fn list(&self, params: ItemVariantPaginationParams) -> Result<ItemVariantPaginatedResult>;

    /// List item_variant with pagination and filters
    async fn list_with_filters(&self, params: ItemVariantPaginationParams, filters: ItemVariantFilter) -> Result<ItemVariantPaginatedResult>;

    /// Count all item_variant entities
    async fn count(&self) -> Result<u64>;

    /// Count item_variant entities matching filters
    async fn count_with_filters(&self, filters: ItemVariantFilter) -> Result<u64>;

    /// Check if item_variant exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete item_variant by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted item_variant by ID
    async fn restore(&self, id: &str) -> Result<Option<ItemVariant>>;

    /// List soft-deleted item_variant entities
    async fn list_deleted(&self, params: ItemVariantPaginationParams) -> Result<ItemVariantPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save item_variant entities
    async fn bulk_save(&self, entities: &[ItemVariant]) -> Result<Vec<ItemVariant>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
