//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.


pub mod attribute_repository;
pub mod attribute_value_repository;
pub mod brand_repository;
pub mod item_repository;
pub mod item_group_repository;
pub mod item_variant_repository;
pub mod uom_repository;
pub mod uom_conversion_repository;

// Re-exports
pub use attribute_repository::{
    AttributeRepository,
    AttributePaginationParams,
    AttributePaginatedResult,
    AttributeFilter,
};
pub use attribute_value_repository::{
    AttributeValueRepository,
    AttributeValuePaginationParams,
    AttributeValuePaginatedResult,
    AttributeValueFilter,
};
pub use brand_repository::{
    BrandRepository,
    BrandPaginationParams,
    BrandPaginatedResult,
    BrandFilter,
};
pub use item_repository::{
    ItemRepository,
    ItemPaginationParams,
    ItemPaginatedResult,
    ItemFilter,
};
pub use item_group_repository::{
    ItemGroupRepository,
    ItemGroupPaginationParams,
    ItemGroupPaginatedResult,
    ItemGroupFilter,
};
pub use item_variant_repository::{
    ItemVariantRepository,
    ItemVariantPaginationParams,
    ItemVariantPaginatedResult,
    ItemVariantFilter,
};
pub use uom_repository::{
    UomRepository,
    UomPaginationParams,
    UomPaginatedResult,
    UomFilter,
};
pub use uom_conversion_repository::{
    UomConversionRepository,
    UomConversionPaginationParams,
    UomConversionPaginatedResult,
    UomConversionFilter,
};
