//! Repository for Attribute entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the catalog write service's attribute SQL (4-layer rule: services orchestrate, repos
//! hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Attribute, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use backbone_orm::company_scope;
use sqlx::PgPool;
use uuid::Uuid;

use crate::domain::entity::Attribute;

/// Table name for Attribute entities
pub const TABLE_NAME: &str = "catalog.attributes";

/// Repository for Attribute entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct AttributeRepository(
    backbone_orm::GenericCrudRepository<Attribute, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for AttributeRepository {
    type Target = backbone_orm::GenericCrudRepository<Attribute, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl AttributeRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a validated attribute insert writes.
pub struct NewAttributeRow<'a> {
    pub id: Uuid,
    pub company_id: Uuid,
    pub code: &'a str,
    pub name: &'a str,
    pub attribute_type: &'a str,
}

/// Catalog attribute SQL. Lives here (not in the service) per the module's 4-layer rule.
impl AttributeRepository {
    /// `EXISTS` probe filtered by company (replaces the prior string-built
    /// `exists_in("attributes", id, company)` helper in the write service). Used for `attribute_id`
    /// FK validation on create-attribute-value.
    pub async fn exists_id_in_company(
        &self,
        pool: &PgPool,
        id: Uuid,
        company: Uuid,
    ) -> Result<bool, sqlx::Error> {
        let found: Option<Uuid> = company_scope::fetch_optional_scalar_scoped(
            pool,
            sqlx::query_scalar(
                "SELECT id FROM catalog.attributes \
                 WHERE id = $1 AND company_id = $2 AND (metadata->>'deleted_at') IS NULL",
            )
            .bind(id)
            .bind(company),
        )
        .await?;
        Ok(found.is_some())
    }

    /// Resolve an attribute id by code (used by create-item-variant to disambiguate an unknown
    /// axis from an unknown value). `company_id = $2` only — the company is on the caller's scope.
    pub async fn find_id_by_code(
        &self,
        pool: &PgPool,
        code: &str,
        company: Uuid,
    ) -> Result<Option<Uuid>, sqlx::Error> {
        let id: Option<Uuid> = company_scope::fetch_optional_scalar_scoped(
            pool,
            sqlx::query_scalar(
                "SELECT id FROM catalog.attributes \
                 WHERE code=$1 AND company_id=$2 AND (metadata->>'deleted_at') IS NULL",
            )
            .bind(code)
            .bind(company),
        )
        .await?;
        Ok(id)
    }

    /// Insert a validated attribute row. The statement runs through the `company_scope` execute
    /// helper, which binds `app.company_id` so the RLS `WITH CHECK` on `catalog.attributes`
    /// accepts the row. Unique-constraint errors propagate as `sqlx::Error` so the service can
    /// disambiguate code duplicates.
    pub async fn insert_attribute(
        &self,
        pool: &PgPool,
        r: &NewAttributeRow<'_>,
    ) -> Result<(), sqlx::Error> {
        company_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"INSERT INTO catalog.attributes (id, company_id, code, name, attribute_type, status)
                   VALUES ($1,$2,$3,$4,$5::attribute_type,'active'::catalog_status)"#,
            )
            .bind(r.id)
            .bind(r.company_id)
            .bind(r.code)
            .bind(r.name)
            .bind(r.attribute_type),
        )
        .await?;
        Ok(())
    }
}

backbone_core::impl_crud_repository!(AttributeRepository, Attribute, soft_delete);
