//! Repository for AttributeValue entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<AttributeValue, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::AttributeValue;

/// Table name for AttributeValue entities
pub const TABLE_NAME: &str = "catalog.attribute_values";

/// Repository for AttributeValue entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct AttributeValueRepository(
    backbone_orm::GenericCrudRepository<AttributeValue, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for AttributeValueRepository {
    type Target = backbone_orm::GenericCrudRepository<AttributeValue, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl AttributeValueRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(AttributeValueRepository, AttributeValue, soft_delete);
