//! Repository for Brand entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Brand, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::Brand;

/// Table name for Brand entities
pub const TABLE_NAME: &str = "catalog.brands";

/// Repository for Brand entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct BrandRepository(
    backbone_orm::GenericCrudRepository<Brand, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for BrandRepository {
    type Target = backbone_orm::GenericCrudRepository<Brand, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl BrandRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(BrandRepository, Brand, soft_delete);
