//! Repository for ItemVariant entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the catalog write service's variant SQL (4-layer rule: services orchestrate, repos
//! hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<ItemVariant, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use rust_decimal::Decimal;
use sqlx::{PgConnection, PgPool};
use uuid::Uuid;

use crate::domain::entity::ItemVariant;
use crate::infrastructure::persistence::item_repository::ItemHit;

/// Table name for ItemVariant entities
pub const TABLE_NAME: &str = "catalog.item_variants";

/// Repository for ItemVariant entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct ItemVariantRepository(
    backbone_orm::GenericCrudRepository<ItemVariant, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for ItemVariantRepository {
    type Target = backbone_orm::GenericCrudRepository<ItemVariant, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl ItemVariantRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a validated item-variant insert writes. `options` is the JSON-encoded
/// `{attribute_code: value_code}` map validated against the attribute registry by the caller.
pub struct NewItemVariantRow<'a> {
    pub id: Uuid,
    pub company_id: Uuid,
    pub item_id: Uuid,
    pub sku: &'a str,
    pub variant_label: &'a str,
    pub options: &'a serde_json::Value,
    pub barcode: Option<&'a str>,
    pub is_default: bool,
    pub weight_per_unit: Option<Decimal>,
}

/// Catalog variant SQL. Lives here (not in the service) per the module's 4-layer rule.
impl ItemVariantRepository {
    /// Resolve a scanned code (barcode OR SKU) to a variant, joined with its parent item for the
    /// sellable identity. Per-company (ADR-0010 B1): same `($2::uuid IS NULL OR …)` shape as
    /// [`ItemRepository::find_by_scan_code`].
    pub async fn find_variant_by_scan_code(
        &self,
        pool: &PgPool,
        code: &str,
        company: Option<Uuid>,
    ) -> Result<Option<ItemHit>, sqlx::Error> {
        let hit = sqlx::query_as::<_, ItemHit>(
            r#"SELECT v.item_id, v.id AS variant_id, i.item_code, i.name, v.barcode, v.sku
               FROM catalog.item_variants v JOIN catalog.items i ON i.id = v.item_id
               WHERE (v.barcode = $1 OR v.sku = $1)
                 AND ($2::uuid IS NULL OR v.company_id = $2)
                 AND (v.metadata->>'deleted_at') IS NULL
               LIMIT 1"#,
        )
        .bind(code)
        .bind(company)
        .fetch_optional(pool)
        .await?;
        Ok(hit)
    }

    /// Resolve `item_id` for a live variant (the soft-delete lookup step in
    /// `CatalogWriteService::delete_item_variant`). `company_id = $2` only — the company is on the
    /// caller's scope already.
    pub async fn find_item_id_for_live(
        &self,
        pool: &PgPool,
        variant_id: Uuid,
        company: Uuid,
    ) -> Result<Option<Uuid>, sqlx::Error> {
        let item_id: Option<Uuid> = sqlx::query_scalar(
            "SELECT item_id FROM catalog.item_variants \
             WHERE id=$1 AND company_id=$2 AND (metadata->>'deleted_at') IS NULL",
        )
        .bind(variant_id)
        .bind(company)
        .fetch_optional(pool)
        .await?;
        Ok(item_id)
    }

    /// Insert a variant on the caller's tx. The caller has already bound the company on `conn`.
    /// Unique-constraint errors propagate as `sqlx::Error` so the service can disambiguate barcode
    /// vs SKU duplicates.
    pub async fn insert_variant(
        &self,
        conn: &mut PgConnection,
        r: &NewItemVariantRow<'_>,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO catalog.item_variants
                (id, company_id, item_id, sku, variant_label, options, barcode, is_default, weight_per_unit, status)
               VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,'active'::catalog_status)"#,
        )
        .bind(r.id)
        .bind(r.company_id)
        .bind(r.item_id)
        .bind(r.sku)
        .bind(r.variant_label)
        .bind(r.options)
        .bind(r.barcode)
        .bind(r.is_default)
        .bind(r.weight_per_unit)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Soft-delete a variant on the caller's tx. The caller has already bound the company on `conn`;
    /// `company_id = $2` is defense-in-depth on top of the RLS fence.
    pub async fn soft_delete_variant(
        &self,
        conn: &mut PgConnection,
        variant_id: Uuid,
        company: Uuid,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            "UPDATE catalog.item_variants \
             SET metadata = jsonb_set(metadata, '{deleted_at}', to_jsonb(now())) \
             WHERE id=$1 AND company_id=$2",
        )
        .bind(variant_id)
        .bind(company)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Count live variants for an item on the caller's tx (used by `delete_item_variant` to decide
    /// whether to flip `Item.has_variants` back to FALSE). Returns the COUNT.
    pub async fn count_live_variants(
        &self,
        conn: &mut PgConnection,
        item_id: Uuid,
        company: Uuid,
    ) -> Result<i64, sqlx::Error> {
        let remaining: i64 = sqlx::query_scalar(
            "SELECT COUNT(*) FROM catalog.item_variants \
             WHERE item_id=$1 AND company_id=$2 AND (metadata->>'deleted_at') IS NULL",
        )
        .bind(item_id)
        .bind(company)
        .fetch_one(conn)
        .await?;
        Ok(remaining)
    }
}

backbone_core::impl_crud_repository!(ItemVariantRepository, ItemVariant, soft_delete);
