//! Repository for ItemGroup entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<ItemGroup, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::ItemGroup;

/// Table name for ItemGroup entities
pub const TABLE_NAME: &str = "catalog.item_groups";

/// Repository for ItemGroup entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct ItemGroupRepository(
    backbone_orm::GenericCrudRepository<ItemGroup, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for ItemGroupRepository {
    type Target = backbone_orm::GenericCrudRepository<ItemGroup, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl ItemGroupRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(ItemGroupRepository, ItemGroup, soft_delete);
