//! Repository for Item entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the catalog write service's item SQL (4-layer rule: services orchestrate, repos hold
//! SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Item, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use rust_decimal::Decimal;
use sqlx::{PgConnection, PgPool};
use uuid::Uuid;

use crate::domain::entity::Item;

/// Table name for Item entities
pub const TABLE_NAME: &str = "catalog.items";

/// Repository for Item entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct ItemRepository(
    backbone_orm::GenericCrudRepository<Item, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for ItemRepository {
    type Target = backbone_orm::GenericCrudRepository<Item, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl ItemRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// A scan resolved to a sellable identity: the item (always) plus the variant if the scanned code
/// matched a variant SKU/barcode rather than the base item. POS rings against `item_id`.
///
/// Returned by [`ItemRepository::find_by_scan_code`] and
/// [`crate::infrastructure::persistence::ItemVariantRepository::find_variant_by_scan_code`].
#[derive(Debug, Clone, serde::Serialize, sqlx::FromRow)]
pub struct ItemHit {
    pub item_id: Uuid,
    pub variant_id: Option<Uuid>,
    pub item_code: String,
    pub name: String,
    pub barcode: Option<String>,
    pub sku: Option<String>,
}

/// The exact row a validated item insert writes.
pub struct NewItemRow<'a> {
    pub id: Uuid,
    pub company_id: Uuid,
    pub item_code: &'a str,
    pub name: &'a str,
    pub description: Option<&'a str>,
    pub barcode: Option<&'a str>,
    pub brand_id: Option<Uuid>,
    pub item_group_id: Uuid,
    pub default_uom_id: Uuid,
    pub item_type: &'a str,
    pub is_sales_item: bool,
    pub is_purchase_item: bool,
    pub is_stock_item: bool,
    pub hsn_code: Option<&'a str>,
    pub is_taxable: bool,
    pub weight_per_unit: Option<Decimal>,
    pub tags: &'a serde_json::Value,
    pub data: &'a serde_json::Value,
}

/// Catalog item SQL. Lives here (not in the service) per the module's 4-layer rule.
impl ItemRepository {
    /// Resolve a scanned code (barcode OR item_code) to the base item. Per-company (ADR-0010 B1):
    /// `company` is the caller's company (from `current_company()`, set by the request scope) bound
    /// into the lookup as defense-in-depth on top of the RLS fence, so a missed scope still returns
    /// nothing instead of leaking another tenant's item. `company = None` admits rows when no scope
    /// is set (matches the prior bare-pool `fetch_optional` behavior).
    pub async fn find_by_scan_code(
        &self,
        pool: &PgPool,
        code: &str,
        company: Option<Uuid>,
    ) -> Result<Option<ItemHit>, sqlx::Error> {
        let hit = sqlx::query_as::<_, ItemHit>(
            r#"SELECT id AS item_id, NULL::uuid AS variant_id, item_code, name, barcode, NULL::text AS sku
               FROM catalog.items
               WHERE (barcode = $1 OR item_code = $1)
                 AND ($2::uuid IS NULL OR company_id = $2)
                 AND (metadata->>'deleted_at') IS NULL
               LIMIT 1"#,
        )
        .bind(code)
        .bind(company)
        .fetch_optional(pool)
        .await?;
        Ok(hit)
    }

    /// `EXISTS` probe filtered by company (replaces the prior string-built
    /// `exists_in("items", id, company)` helper in the write service). `company_id = $2` is the
    /// only fence (no `IS NULL OR …` here): the validated writes that call this always have a
    /// concrete company on the DTO.
    pub async fn exists_id_in_company(
        &self,
        pool: &PgPool,
        id: Uuid,
        company: Uuid,
    ) -> Result<bool, sqlx::Error> {
        let found: Option<Uuid> = sqlx::query_scalar(
            "SELECT id FROM catalog.items \
             WHERE id = $1 AND company_id = $2 AND (metadata->>'deleted_at') IS NULL",
        )
        .bind(id)
        .bind(company)
        .fetch_optional(pool)
        .await?;
        Ok(found.is_some())
    }

    /// Insert a validated item row on the pool. The caller has already bound the company scope via
    /// `with_company_scope`; the explicit `company_id` in the VALUES list is defense-in-depth on
    /// top of the RLS fence. Unique-constraint errors propagate as `sqlx::Error` so the service can
    /// disambiguate barcode vs item_code duplicates.
    pub async fn insert_item(
        &self,
        pool: &PgPool,
        r: &NewItemRow<'_>,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO catalog.items
                (id, company_id, item_code, name, description, barcode, brand_id, item_group_id,
                 default_uom_id, item_type, is_sales_item, is_purchase_item, is_stock_item,
                 hsn_code, is_taxable, weight_per_unit, tags, data, status)
               VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::item_type,$11,$12,$13,$14,$15,$16,$17,$18,'active'::catalog_status)"#,
        )
        .bind(r.id)
        .bind(r.company_id)
        .bind(r.item_code)
        .bind(r.name)
        .bind(r.description)
        .bind(r.barcode)
        .bind(r.brand_id)
        .bind(r.item_group_id)
        .bind(r.default_uom_id)
        .bind(r.item_type)
        .bind(r.is_sales_item)
        .bind(r.is_purchase_item)
        .bind(r.is_stock_item)
        .bind(r.hsn_code)
        .bind(r.is_taxable)
        .bind(r.weight_per_unit)
        .bind(r.tags)
        .bind(r.data)
        .execute(pool)
        .await?;
        Ok(())
    }

    /// Flip `has_variants = TRUE` on the item (in-tx; called from the variant-create tx after the
    /// variant row is inserted). The caller has already bound the company on `conn`.
    pub async fn set_has_variants_true(
        &self,
        conn: &mut PgConnection,
        item_id: Uuid,
    ) -> Result<(), sqlx::Error> {
        sqlx::query("UPDATE catalog.items SET has_variants = TRUE WHERE id = $1")
            .bind(item_id)
            .execute(conn)
            .await?;
        Ok(())
    }

    /// Flip `has_variants = FALSE` on the item (in-tx; called from the variant-delete tx when no
    /// live variants remain). The caller has already bound the company on `conn`.
    pub async fn set_has_variants_false(
        &self,
        conn: &mut PgConnection,
        item_id: Uuid,
    ) -> Result<(), sqlx::Error> {
        sqlx::query("UPDATE catalog.items SET has_variants = FALSE WHERE id=$1")
            .bind(item_id)
            .execute(conn)
            .await?;
        Ok(())
    }
}

backbone_core::impl_crud_repository!(ItemRepository, Item, soft_delete);
