//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod attribute_repository;
mod attribute_value_repository;
mod brand_repository;
mod item_repository;
mod item_group_repository;
mod item_variant_repository;
mod uom_repository;
mod uom_conversion_repository;

// Custom persistence modules
// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use attribute_repository::AttributeRepository;
pub use attribute_value_repository::AttributeValueRepository;
pub use brand_repository::BrandRepository;
pub use item_repository::ItemRepository;
pub use item_group_repository::ItemGroupRepository;
pub use item_variant_repository::ItemVariantRepository;
pub use uom_repository::UomRepository;
pub use uom_conversion_repository::UomConversionRepository;

// Re-export backbone-orm types
pub use backbone_orm::repository::{
    DatabaseOperations, PostgresRepository,
    PaginationParams, PaginationInfo, PaginatedResult,
    FilterParams, FilterCondition, SortParams, SortDirection,
};

// Re-export custom persistence types
// <<< CUSTOM
// The hand-written catalog SQL's parameter/projection types. Every repository listed here is
// declared `user_owned` in metaphor.codegen.yaml — see catalog_write_service.rs, which orchestrates
// them.
pub use attribute_repository::NewAttributeRow;
pub use attribute_value_repository::{AttributeValueResolveRow, NewAttributeValueRow};
pub use brand_repository::NewBrandRow;
pub use item_repository::{ItemHit, NewItemRow};
pub use item_group_repository::NewItemGroupRow;
pub use item_variant_repository::NewItemVariantRow;
pub use uom_repository::NewUomRow;
pub use uom_conversion_repository::NewUomConversionRow;
// END CUSTOM
