//! Repository for UomConversion entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the catalog write service's UOM-conversion SQL (4-layer rule: services orchestrate,
//! repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<UomConversion, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use rust_decimal::Decimal;
use sqlx::PgPool;
use uuid::Uuid;

use crate::domain::entity::UomConversion;

/// Table name for UomConversion entities
pub const TABLE_NAME: &str = "catalog.uom_conversions";

/// Repository for UomConversion entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct UomConversionRepository(
    backbone_orm::GenericCrudRepository<UomConversion, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for UomConversionRepository {
    type Target = backbone_orm::GenericCrudRepository<UomConversion, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl UomConversionRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a validated UOM-conversion insert writes.
pub struct NewUomConversionRow {
    pub id: Uuid,
    pub company_id: Uuid,
    pub from_uom_id: Uuid,
    pub to_uom_id: Uuid,
    pub factor: Decimal,
}

/// Catalog UOM-conversion SQL. Lives here (not in the service) per the module's 4-layer rule.
impl UomConversionRepository {
    /// Insert a validated UOM-conversion row on the pool. The caller has already bound the company
    /// scope via `with_company_scope`. Unique-constraint errors propagate as `sqlx::Error` so the
    /// service can flag a duplicate conversion.
    pub async fn insert_uom_conversion(
        &self,
        pool: &PgPool,
        r: &NewUomConversionRow,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO catalog.uom_conversions (id, company_id, from_uom_id, to_uom_id, factor)
               VALUES ($1,$2,$3,$4,$5)"#,
        )
        .bind(r.id)
        .bind(r.company_id)
        .bind(r.from_uom_id)
        .bind(r.to_uom_id)
        .bind(r.factor)
        .execute(pool)
        .await?;
        Ok(())
    }

    /// Does a live conversion `from_uom → to_uom` exist for this company? (RLS scopes the read;
    /// also filtered explicitly by `company_id`.)
    pub async fn pair_exists(
        &self,
        pool: &PgPool,
        company: Uuid,
        from_uom: Uuid,
        to_uom: Uuid,
    ) -> Result<bool, sqlx::Error> {
        let exists: bool = sqlx::query_scalar(
            "SELECT EXISTS (SELECT 1 FROM catalog.uom_conversions \
             WHERE company_id=$1 AND from_uom_id=$2 AND to_uom_id=$3 \
             AND (metadata->>'deleted_at') IS NULL)",
        )
        .bind(company)
        .bind(from_uom)
        .bind(to_uom)
        .fetch_one(pool)
        .await?;
        Ok(exists)
    }

    /// Resolve a conversion factor between two units in EITHER direction: the direct row
    /// (`from_uom → to_uom = factor`) if present, else the inverse (`1/factor`) of the reverse row
    /// (`to_uom → from_uom`). `None` if no live conversion links the two units for this company.
    /// UomConversion is stored one-directional; this makes it usable both ways (council finding).
    pub async fn factor_between(
        &self,
        pool: &PgPool,
        company: Uuid,
        from_uom: Uuid,
        to_uom: Uuid,
    ) -> Result<Option<Decimal>, sqlx::Error> {
        // Direct: 1 from_uom = factor to_uom.
        let direct: Option<Decimal> = sqlx::query_scalar(
            "SELECT factor FROM catalog.uom_conversions \
             WHERE company_id=$1 AND from_uom_id=$2 AND to_uom_id=$3 \
             AND (metadata->>'deleted_at') IS NULL",
        )
        .bind(company)
        .bind(from_uom)
        .bind(to_uom)
        .fetch_optional(pool)
        .await?;
        if let Some(f) = direct {
            return Ok(Some(f));
        }
        // Reverse: a row `to_uom → from_uom = f'` means `1 from_uom = (1/f') to_uom`.
        let reverse: Option<Decimal> = sqlx::query_scalar(
            "SELECT factor FROM catalog.uom_conversions \
             WHERE company_id=$1 AND from_uom_id=$2 AND to_uom_id=$3 \
             AND (metadata->>'deleted_at') IS NULL",
        )
        .bind(company)
        .bind(to_uom)
        .bind(from_uom)
        .fetch_optional(pool)
        .await?;
        Ok(reverse.map(|f| Decimal::ONE / f))
    }
}

backbone_core::impl_crud_repository!(UomConversionRepository, UomConversion, soft_delete);
