//! Repository for Uom entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the catalog write service's UOM SQL (4-layer rule: services orchestrate, repos hold
//! SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Uom, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use sqlx::PgPool;
use uuid::Uuid;

use crate::domain::entity::Uom;

/// Table name for Uom entities
pub const TABLE_NAME: &str = "catalog.uoms";

/// Repository for Uom entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct UomRepository(
    backbone_orm::GenericCrudRepository<Uom, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for UomRepository {
    type Target = backbone_orm::GenericCrudRepository<Uom, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl UomRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a validated UOM insert writes.
pub struct NewUomRow<'a> {
    pub id: Uuid,
    pub company_id: Uuid,
    pub code: &'a str,
    pub name: &'a str,
    pub uom_type: &'a str,
    pub decimal_places: i32,
}

/// Catalog UOM SQL. Lives here (not in the service) per the module's 4-layer rule.
impl UomRepository {
    /// `EXISTS` probe filtered by company (replaces the prior string-built
    /// `exists_in("uoms", id, company)` helper in the write service). Used for default_uom_id FK
    /// validation on create-item and from/to UOM validation on create-uom-conversion.
    pub async fn exists_id_in_company(
        &self,
        pool: &PgPool,
        id: Uuid,
        company: Uuid,
    ) -> Result<bool, sqlx::Error> {
        let found: Option<Uuid> = sqlx::query_scalar(
            "SELECT id FROM catalog.uoms \
             WHERE id = $1 AND company_id = $2 AND (metadata->>'deleted_at') IS NULL",
        )
        .bind(id)
        .bind(company)
        .fetch_optional(pool)
        .await?;
        Ok(found.is_some())
    }

    /// Insert a validated UOM row on the pool. The caller has already bound the company scope via
    /// `with_company_scope`. Unique-constraint errors propagate as `sqlx::Error` so the service can
    /// disambiguate code duplicates.
    pub async fn insert_uom(
        &self,
        pool: &PgPool,
        r: &NewUomRow<'_>,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO catalog.uoms (id, company_id, code, name, uom_type, decimal_places, status)
               VALUES ($1,$2,$3,$4,$5::uom_type,$6,'active'::catalog_status)"#,
        )
        .bind(r.id)
        .bind(r.company_id)
        .bind(r.code)
        .bind(r.name)
        .bind(r.uom_type)
        .bind(r.decimal_places)
        .execute(pool)
        .await?;
        Ok(())
    }
}

backbone_core::impl_crud_repository!(UomRepository, Uom, soft_delete);
