//! Validator for Attribute entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Attribute>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::Attribute;

/// Validator type alias for Attribute entities.
pub type AttributeValidator = EntityValidator<Attribute>;

/// Build a validator for Attribute with all schema-defined field rules.
pub fn attribute_validator() -> AttributeValidator {
    EntityValidator::new()
        .rule(RequiredString::new("code", |e: &Attribute| &e.code))
        .rule(RequiredString::new("name", |e: &Attribute| &e.name))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
