//! Validator for Brand entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Brand>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::Brand;

/// Validator type alias for Brand entities.
pub type BrandValidator = EntityValidator<Brand>;

/// Build a validator for Brand with all schema-defined field rules.
pub fn brand_validator() -> BrandValidator {
    EntityValidator::new()
        .rule(RequiredString::new("code", |e: &Brand| &e.code))
        .rule(RequiredString::new("name", |e: &Brand| &e.name))
        .rule(OptionalNotBlank::new("short_description", |e: &Brand| e.short_description.as_deref()))
        .rule(OptionalNotBlank::new("description", |e: &Brand| e.description.as_deref()))
        .rule(OptionalNotBlank::new("logo_url", |e: &Brand| e.logo_url.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
