//! Validator for ItemGroup entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<ItemGroup>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, RequiredString};
use crate::domain::entity::ItemGroup;

/// Validator type alias for ItemGroup entities.
pub type ItemGroupValidator = EntityValidator<ItemGroup>;

/// Build a validator for ItemGroup with all schema-defined field rules.
pub fn item_group_validator() -> ItemGroupValidator {
    EntityValidator::new()
        .rule(RequiredString::new("code", |e: &ItemGroup| &e.code))
        .rule(RequiredString::new("name", |e: &ItemGroup| &e.name))
        .rule(NonNegative::new("level", |e: &ItemGroup| e.level as i64))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
