//! Validator for ItemVariant entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<ItemVariant>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::ItemVariant;

/// Validator type alias for ItemVariant entities.
pub type ItemVariantValidator = EntityValidator<ItemVariant>;

/// Build a validator for ItemVariant with all schema-defined field rules.
pub fn item_variant_validator() -> ItemVariantValidator {
    EntityValidator::new()
        .rule(RequiredString::new("sku", |e: &ItemVariant| &e.sku))
        .rule(RequiredString::new("variant_label", |e: &ItemVariant| &e.variant_label))
        .rule(OptionalNotBlank::new("barcode", |e: &ItemVariant| e.barcode.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
