//! Validator for Item entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Item>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank, RequiredString};
use crate::domain::entity::Item;

/// Validator type alias for Item entities.
pub type ItemValidator = EntityValidator<Item>;

/// Build a validator for Item with all schema-defined field rules.
pub fn item_validator() -> ItemValidator {
    EntityValidator::new()
        .rule(RequiredString::new("item_code", |e: &Item| &e.item_code))
        .rule(RequiredString::new("name", |e: &Item| &e.name))
        .rule(OptionalNotBlank::new("description", |e: &Item| e.description.as_deref()))
        .rule(OptionalNotBlank::new("barcode", |e: &Item| e.barcode.as_deref()))
        .rule(OptionalNotBlank::new("hsn_code", |e: &Item| e.hsn_code.as_deref()))
        .rule(OptionalNotBlank::new("sni", |e: &Item| e.sni.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
