//! Validator for UomConversion entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<UomConversion>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use crate::domain::entity::UomConversion;

/// Validator type alias for UomConversion entities.
pub type UomConversionValidator = EntityValidator<UomConversion>;

/// Build a validator for UomConversion with all schema-defined field rules.
pub fn uom_conversion_validator() -> UomConversionValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
