//! Validator for Uom entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Uom>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, RequiredString};
use crate::domain::entity::Uom;

/// Validator type alias for Uom entities.
pub type UomValidator = EntityValidator<Uom>;

/// Build a validator for Uom with all schema-defined field rules.
pub fn uom_validator() -> UomValidator {
    EntityValidator::new()
        .rule(RequiredString::new("code", |e: &Uom| &e.code))
        .rule(RequiredString::new("name", |e: &Uom| &e.name))
        .rule(NonNegative::new("decimal_places", |e: &Uom| e.decimal_places as i64))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
