//! Auth configuration for AttributeValue handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<AttributeValue>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::AttributeValueService;
use crate::domain::entity::AttributeValue;

/// Permission string constants for AttributeValue operations.
pub mod permissions {
    pub const LIST:        &str = "attribute_value:list";
    pub const READ:        &str = "attribute_value:read";
    pub const CREATE:      &str = "attribute_value:create";
    pub const UPDATE:      &str = "attribute_value:update";
    pub const DELETE:      &str = "attribute_value:delete";
    pub const RESTORE:     &str = "attribute_value:restore";
    pub const TRASH:       &str = "attribute_value:trash";
    pub const EMPTY_TRASH: &str = "attribute_value:empty_trash";
    pub const BULK_CREATE: &str = "attribute_value:bulk_create";
    pub const UPSERT:      &str = "attribute_value:upsert";
}

/// Resource policy for AttributeValue — maps CRUD actions to permission strings.
pub struct AttributeValuePolicy;

#[async_trait]
impl ResourcePolicy<AttributeValue> for AttributeValuePolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &AttributeValue,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for AttributeValue handlers.
///
/// Wraps `AttributeValueService` and checks `AttributeValuePolicy` before delegating.
pub type AttributeValueGuard = PermissionGuard<AttributeValue>;

/// Service-integrated permission guard for AttributeValue (for use in generated handlers).
pub type AttributeValueServiceGuard = ServicePermissionGuard<AttributeValue, AttributeValueService, AttributeValuePolicy>;

// <<< CUSTOM
// END CUSTOM
