//! Auth configuration for Attribute handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Attribute>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::AttributeService;
use crate::domain::entity::Attribute;

/// Permission string constants for Attribute operations.
pub mod permissions {
    pub const LIST:        &str = "attribute:list";
    pub const READ:        &str = "attribute:read";
    pub const CREATE:      &str = "attribute:create";
    pub const UPDATE:      &str = "attribute:update";
    pub const DELETE:      &str = "attribute:delete";
    pub const RESTORE:     &str = "attribute:restore";
    pub const TRASH:       &str = "attribute:trash";
    pub const EMPTY_TRASH: &str = "attribute:empty_trash";
    pub const BULK_CREATE: &str = "attribute:bulk_create";
    pub const UPSERT:      &str = "attribute:upsert";
}

/// Resource policy for Attribute — maps CRUD actions to permission strings.
pub struct AttributePolicy;

#[async_trait]
impl ResourcePolicy<Attribute> for AttributePolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Attribute,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Attribute handlers.
///
/// Wraps `AttributeService` and checks `AttributePolicy` before delegating.
pub type AttributeGuard = PermissionGuard<Attribute>;

/// Service-integrated permission guard for Attribute (for use in generated handlers).
pub type AttributeServiceGuard = ServicePermissionGuard<Attribute, AttributeService, AttributePolicy>;

// <<< CUSTOM
// END CUSTOM
