//! Auth configuration for Brand handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Brand>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::BrandService;
use crate::domain::entity::Brand;

/// Permission string constants for Brand operations.
pub mod permissions {
    pub const LIST:        &str = "brand:list";
    pub const READ:        &str = "brand:read";
    pub const CREATE:      &str = "brand:create";
    pub const UPDATE:      &str = "brand:update";
    pub const DELETE:      &str = "brand:delete";
    pub const RESTORE:     &str = "brand:restore";
    pub const TRASH:       &str = "brand:trash";
    pub const EMPTY_TRASH: &str = "brand:empty_trash";
    pub const BULK_CREATE: &str = "brand:bulk_create";
    pub const UPSERT:      &str = "brand:upsert";
}

/// Resource policy for Brand — maps CRUD actions to permission strings.
pub struct BrandPolicy;

#[async_trait]
impl ResourcePolicy<Brand> for BrandPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Brand,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Brand handlers.
///
/// Wraps `BrandService` and checks `BrandPolicy` before delegating.
pub type BrandGuard = PermissionGuard<Brand>;

/// Service-integrated permission guard for Brand (for use in generated handlers).
pub type BrandServiceGuard = ServicePermissionGuard<Brand, BrandService, BrandPolicy>;

// <<< CUSTOM
// END CUSTOM
