//! Auth configuration for ItemVariant handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<ItemVariant>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::ItemVariantService;
use crate::domain::entity::ItemVariant;

/// Permission string constants for ItemVariant operations.
pub mod permissions {
    pub const LIST:        &str = "item_variant:list";
    pub const READ:        &str = "item_variant:read";
    pub const CREATE:      &str = "item_variant:create";
    pub const UPDATE:      &str = "item_variant:update";
    pub const DELETE:      &str = "item_variant:delete";
    pub const RESTORE:     &str = "item_variant:restore";
    pub const TRASH:       &str = "item_variant:trash";
    pub const EMPTY_TRASH: &str = "item_variant:empty_trash";
    pub const BULK_CREATE: &str = "item_variant:bulk_create";
    pub const UPSERT:      &str = "item_variant:upsert";
}

/// Resource policy for ItemVariant — maps CRUD actions to permission strings.
pub struct ItemVariantPolicy;

#[async_trait]
impl ResourcePolicy<ItemVariant> for ItemVariantPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &ItemVariant,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for ItemVariant handlers.
///
/// Wraps `ItemVariantService` and checks `ItemVariantPolicy` before delegating.
pub type ItemVariantGuard = PermissionGuard<ItemVariant>;

/// Service-integrated permission guard for ItemVariant (for use in generated handlers).
pub type ItemVariantServiceGuard = ServicePermissionGuard<ItemVariant, ItemVariantService, ItemVariantPolicy>;

// <<< CUSTOM
// END CUSTOM
