//! Auth configuration for ItemGroup handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<ItemGroup>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::ItemGroupService;
use crate::domain::entity::ItemGroup;

/// Permission string constants for ItemGroup operations.
pub mod permissions {
    pub const LIST:        &str = "item_group:list";
    pub const READ:        &str = "item_group:read";
    pub const CREATE:      &str = "item_group:create";
    pub const UPDATE:      &str = "item_group:update";
    pub const DELETE:      &str = "item_group:delete";
    pub const RESTORE:     &str = "item_group:restore";
    pub const TRASH:       &str = "item_group:trash";
    pub const EMPTY_TRASH: &str = "item_group:empty_trash";
    pub const BULK_CREATE: &str = "item_group:bulk_create";
    pub const UPSERT:      &str = "item_group:upsert";
}

/// Resource policy for ItemGroup — maps CRUD actions to permission strings.
pub struct ItemGroupPolicy;

#[async_trait]
impl ResourcePolicy<ItemGroup> for ItemGroupPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &ItemGroup,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for ItemGroup handlers.
///
/// Wraps `ItemGroupService` and checks `ItemGroupPolicy` before delegating.
pub type ItemGroupGuard = PermissionGuard<ItemGroup>;

/// Service-integrated permission guard for ItemGroup (for use in generated handlers).
pub type ItemGroupServiceGuard = ServicePermissionGuard<ItemGroup, ItemGroupService, ItemGroupPolicy>;

// <<< CUSTOM
// END CUSTOM
