//! Auth configuration for Item handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Item>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::ItemService;
use crate::domain::entity::Item;

/// Permission string constants for Item operations.
pub mod permissions {
    pub const LIST:        &str = "item:list";
    pub const READ:        &str = "item:read";
    pub const CREATE:      &str = "item:create";
    pub const UPDATE:      &str = "item:update";
    pub const DELETE:      &str = "item:delete";
    pub const RESTORE:     &str = "item:restore";
    pub const TRASH:       &str = "item:trash";
    pub const EMPTY_TRASH: &str = "item:empty_trash";
    pub const BULK_CREATE: &str = "item:bulk_create";
    pub const UPSERT:      &str = "item:upsert";
}

/// Resource policy for Item — maps CRUD actions to permission strings.
pub struct ItemPolicy;

#[async_trait]
impl ResourcePolicy<Item> for ItemPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Item,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Item handlers.
///
/// Wraps `ItemService` and checks `ItemPolicy` before delegating.
pub type ItemGuard = PermissionGuard<Item>;

/// Service-integrated permission guard for Item (for use in generated handlers).
pub type ItemServiceGuard = ServicePermissionGuard<Item, ItemService, ItemPolicy>;

// <<< CUSTOM
// END CUSTOM
