//! Auth policies and guards
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod attribute_auth;
pub mod attribute_value_auth;
pub mod brand_auth;
pub mod item_auth;
pub mod item_group_auth;
pub mod item_variant_auth;
pub mod uom_auth;
pub mod uom_conversion_auth;

pub use attribute_auth::{AttributePolicy, AttributeGuard, AttributeServiceGuard};
pub use attribute_value_auth::{AttributeValuePolicy, AttributeValueGuard, AttributeValueServiceGuard};
pub use brand_auth::{BrandPolicy, BrandGuard, BrandServiceGuard};
pub use item_auth::{ItemPolicy, ItemGuard, ItemServiceGuard};
pub use item_group_auth::{ItemGroupPolicy, ItemGroupGuard, ItemGroupServiceGuard};
pub use item_variant_auth::{ItemVariantPolicy, ItemVariantGuard, ItemVariantServiceGuard};
pub use uom_auth::{UomPolicy, UomGuard, UomServiceGuard};
pub use uom_conversion_auth::{UomConversionPolicy, UomConversionGuard, UomConversionServiceGuard};

// <<< CUSTOM
// END CUSTOM
