//! Auth configuration for Uom handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Uom>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::UomService;
use crate::domain::entity::Uom;

/// Permission string constants for Uom operations.
pub mod permissions {
    pub const LIST:        &str = "uom:list";
    pub const READ:        &str = "uom:read";
    pub const CREATE:      &str = "uom:create";
    pub const UPDATE:      &str = "uom:update";
    pub const DELETE:      &str = "uom:delete";
    pub const RESTORE:     &str = "uom:restore";
    pub const TRASH:       &str = "uom:trash";
    pub const EMPTY_TRASH: &str = "uom:empty_trash";
    pub const BULK_CREATE: &str = "uom:bulk_create";
    pub const UPSERT:      &str = "uom:upsert";
}

/// Resource policy for Uom — maps CRUD actions to permission strings.
pub struct UomPolicy;

#[async_trait]
impl ResourcePolicy<Uom> for UomPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Uom,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Uom handlers.
///
/// Wraps `UomService` and checks `UomPolicy` before delegating.
pub type UomGuard = PermissionGuard<Uom>;

/// Service-integrated permission guard for Uom (for use in generated handlers).
pub type UomServiceGuard = ServicePermissionGuard<Uom, UomService, UomPolicy>;

// <<< CUSTOM
// END CUSTOM
