//! Auth configuration for UomConversion handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<UomConversion>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::UomConversionService;
use crate::domain::entity::UomConversion;

/// Permission string constants for UomConversion operations.
pub mod permissions {
    pub const LIST:        &str = "uom_conversion:list";
    pub const READ:        &str = "uom_conversion:read";
    pub const CREATE:      &str = "uom_conversion:create";
    pub const UPDATE:      &str = "uom_conversion:update";
    pub const DELETE:      &str = "uom_conversion:delete";
    pub const RESTORE:     &str = "uom_conversion:restore";
    pub const TRASH:       &str = "uom_conversion:trash";
    pub const EMPTY_TRASH: &str = "uom_conversion:empty_trash";
    pub const BULK_CREATE: &str = "uom_conversion:bulk_create";
    pub const UPSERT:      &str = "uom_conversion:upsert";
}

/// Resource policy for UomConversion — maps CRUD actions to permission strings.
pub struct UomConversionPolicy;

#[async_trait]
impl ResourcePolicy<UomConversion> for UomConversionPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &UomConversion,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for UomConversion handlers.
///
/// Wraps `UomConversionService` and checks `UomConversionPolicy` before delegating.
pub type UomConversionGuard = PermissionGuard<UomConversion>;

/// Service-integrated permission guard for UomConversion (for use in generated handlers).
pub type UomConversionServiceGuard = ServicePermissionGuard<UomConversion, UomConversionService, UomConversionPolicy>;

// <<< CUSTOM
// END CUSTOM
