//! AttributeValue API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the AttributeValue CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// ATTRIBUTEVALUE TEST DATA GENERATOR
// ============================================================================

/// Test data generator for AttributeValue
pub struct AttributeValueTestData;

impl TestDataGenerator for AttributeValueTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "attribute_id": Uuid::new_v4().to_string(),
            "code": format!("TEST_{}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "label": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "label_en": null,
            "swatch_hex": null,
            "icon": null,
            "sort_order": 1,
            "status": "active",
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "attribute_id": Uuid::new_v4().to_string(),
            "code": format!("TEST_{}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "label": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "label_en": null,
            "swatch_hex": null,
            "icon": null,
            "sort_order": 1,
            "status": "active",
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/attributes", &super::attribute_api_test::AttributeTestData).await {
            deps.push(("attribute_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// ATTRIBUTEVALUE API TEST
// ============================================================================

/// AttributeValue API test suite
pub struct AttributeValueApiTest {
    inner: GenericCrudTest<AttributeValueTestData>,
}

impl AttributeValueApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/attribute_values", "AttributeValue");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, AttributeValueTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for AttributeValueApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_attribute_value_crud() {
        let mut test = AttributeValueApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add AttributeValue specific tests here
// <<< CUSTOM TESTS END >>>
