//! Brand API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the Brand CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// BRAND TEST DATA GENERATOR
// ============================================================================

/// Test data generator for Brand
pub struct BrandTestData;

impl TestDataGenerator for BrandTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "code": format!("TEST_{}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "short_description": null,
            "description": null,
            "logo_url": null,
            "sort_order": 1,
            "status": "active",
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "code": format!("TEST_{}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "short_description": null,
            "description": null,
            "logo_url": null,
            "sort_order": 1,
            "status": "active",
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// BRAND API TEST
// ============================================================================

/// Brand API test suite
pub struct BrandApiTest {
    inner: GenericCrudTest<BrandTestData>,
}

impl BrandApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/brands", "Brand");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, BrandTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for BrandApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_brand_crud() {
        let mut test = BrandApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add Brand specific tests here
// <<< CUSTOM TESTS END >>>
