//! Item API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the Item CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// ITEM TEST DATA GENERATOR
// ============================================================================

/// Test data generator for Item
pub struct ItemTestData;

impl TestDataGenerator for ItemTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "item_code": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "description": null,
            "barcode": null,
            "brand_id": null,
            "item_group_id": Uuid::new_v4().to_string(),
            "default_uom_id": Uuid::new_v4().to_string(),
            "item_type": "physical_good",
            "is_sales_item": false,
            "is_purchase_item": false,
            "is_stock_item": false,
            "has_variants": false,
            "hsn_code": null,
            "sni": null,
            "is_taxable": false,
            "weight_per_unit": null,
            "shelf_life_days": null,
            "tags": json!({}),
            "data": json!({}),
            "status": "active",
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "item_code": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "description": null,
            "barcode": null,
            "brand_id": null,
            "item_group_id": Uuid::new_v4().to_string(),
            "default_uom_id": Uuid::new_v4().to_string(),
            "item_type": "physical_good",
            "is_sales_item": false,
            "is_purchase_item": false,
            "is_stock_item": false,
            "has_variants": false,
            "hsn_code": null,
            "sni": null,
            "is_taxable": false,
            "weight_per_unit": null,
            "shelf_life_days": null,
            "tags": json!({}),
            "data": json!({}),
            "status": "active",
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/item_groups", &super::item_group_api_test::ItemGroupTestData).await {
            deps.push(("item_group_id".to_string(), id));
        }
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/uoms", &super::uom_api_test::UomTestData).await {
            deps.push(("default_uom_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// ITEM API TEST
// ============================================================================

/// Item API test suite
pub struct ItemApiTest {
    inner: GenericCrudTest<ItemTestData>,
}

impl ItemApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/items", "Item");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, ItemTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for ItemApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_item_crud() {
        let mut test = ItemApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add Item specific tests here
// <<< CUSTOM TESTS END >>>
