//! ItemGroup API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the ItemGroup CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// ITEMGROUP TEST DATA GENERATOR
// ============================================================================

/// Test data generator for ItemGroup
pub struct ItemGroupTestData;

impl TestDataGenerator for ItemGroupTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "code": format!("TEST_{}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "parent_id": null,
            "is_group": false,
            "level": 1,
            "sort_order": 1,
            "status": "active",
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "code": format!("TEST_{}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "parent_id": null,
            "is_group": false,
            "level": 1,
            "sort_order": 1,
            "status": "active",
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// ITEMGROUP API TEST
// ============================================================================

/// ItemGroup API test suite
pub struct ItemGroupApiTest {
    inner: GenericCrudTest<ItemGroupTestData>,
}

impl ItemGroupApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/item_groups", "ItemGroup");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, ItemGroupTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for ItemGroupApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_item_group_crud() {
        let mut test = ItemGroupApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add ItemGroup specific tests here
// <<< CUSTOM TESTS END >>>
