//! ItemVariant API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the ItemVariant CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// ITEMVARIANT TEST DATA GENERATOR
// ============================================================================

/// Test data generator for ItemVariant
pub struct ItemVariantTestData;

impl TestDataGenerator for ItemVariantTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "item_id": Uuid::new_v4().to_string(),
            "sku": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "variant_label": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "options": json!({}),
            "barcode": null,
            "is_default": false,
            "weight_per_unit": null,
            "status": "active",
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "item_id": Uuid::new_v4().to_string(),
            "sku": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "variant_label": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "options": json!({}),
            "barcode": null,
            "is_default": false,
            "weight_per_unit": null,
            "status": "active",
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/items", &super::item_api_test::ItemTestData).await {
            deps.push(("item_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// ITEMVARIANT API TEST
// ============================================================================

/// ItemVariant API test suite
pub struct ItemVariantApiTest {
    inner: GenericCrudTest<ItemVariantTestData>,
}

impl ItemVariantApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/item_variants", "ItemVariant");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, ItemVariantTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for ItemVariantApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_item_variant_crud() {
        let mut test = ItemVariantApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add ItemVariant specific tests here
// <<< CUSTOM TESTS END >>>
