//! Integration Test Implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Contains CRUD API tests for all entities.

pub mod crud_test_base;

pub mod attribute_api_test;
pub mod attribute_value_api_test;
pub mod brand_api_test;
pub mod item_api_test;
pub mod item_group_api_test;
pub mod item_variant_api_test;
pub mod uom_api_test;
pub mod uom_conversion_api_test;

// Re-exports for convenience
pub use crud_test_base::*;
pub use attribute_api_test::*;
pub use attribute_value_api_test::*;
pub use brand_api_test::*;
pub use item_api_test::*;
pub use item_group_api_test::*;
pub use item_variant_api_test::*;
pub use uom_api_test::*;
pub use uom_conversion_api_test::*;
