//! Catalog Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Catalog exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use catalog::exports::{AttributeDto, CatalogQueryService};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `AttributeDto` - Data transfer object for Attribute
/// - `AttributeSummary` - Summary view of Attribute
/// - `AttributeId` - Type-safe ID wrapper
/// - `AttributeValueDto` - Data transfer object for AttributeValue
/// - `AttributeValueSummary` - Summary view of AttributeValue
/// - `AttributeValueId` - Type-safe ID wrapper
/// - `BrandDto` - Data transfer object for Brand
/// - `BrandSummary` - Summary view of Brand
/// - `BrandId` - Type-safe ID wrapper
/// - `ItemDto` - Data transfer object for Item
/// - `ItemSummary` - Summary view of Item
/// - `ItemId` - Type-safe ID wrapper
/// - `ItemGroupDto` - Data transfer object for ItemGroup
/// - `ItemGroupSummary` - Summary view of ItemGroup
/// - `ItemGroupId` - Type-safe ID wrapper
/// - `ItemVariantDto` - Data transfer object for ItemVariant
/// - `ItemVariantSummary` - Summary view of ItemVariant
/// - `ItemVariantId` - Type-safe ID wrapper
/// - `UomDto` - Data transfer object for Uom
/// - `UomSummary` - Summary view of Uom
/// - `UomId` - Type-safe ID wrapper
/// - `UomConversionDto` - Data transfer object for UomConversion
/// - `UomConversionSummary` - Summary view of UomConversion
/// - `UomConversionId` - Type-safe ID wrapper
///
/// ## Public Services
/// - `CatalogQueryService` - Read-only queries
///
/// ## Public Events
/// - `AttributeCreatedEvent` - Published when Attribute is created
/// - `AttributeUpdatedEvent` - Published when Attribute is updated
/// - `AttributeDeletedEvent` - Published when Attribute is deleted
/// - `AttributeValueCreatedEvent` - Published when AttributeValue is created
/// - `AttributeValueUpdatedEvent` - Published when AttributeValue is updated
/// - `AttributeValueDeletedEvent` - Published when AttributeValue is deleted
/// - `BrandCreatedEvent` - Published when Brand is created
/// - `BrandUpdatedEvent` - Published when Brand is updated
/// - `BrandDeletedEvent` - Published when Brand is deleted
/// - `ItemCreatedEvent` - Published when Item is created
/// - `ItemUpdatedEvent` - Published when Item is updated
/// - `ItemDeletedEvent` - Published when Item is deleted
/// - `ItemGroupCreatedEvent` - Published when ItemGroup is created
/// - `ItemGroupUpdatedEvent` - Published when ItemGroup is updated
/// - `ItemGroupDeletedEvent` - Published when ItemGroup is deleted
/// - `ItemVariantCreatedEvent` - Published when ItemVariant is created
/// - `ItemVariantUpdatedEvent` - Published when ItemVariant is updated
/// - `ItemVariantDeletedEvent` - Published when ItemVariant is deleted
/// - `UomCreatedEvent` - Published when Uom is created
/// - `UomUpdatedEvent` - Published when Uom is updated
/// - `UomDeletedEvent` - Published when Uom is deleted
/// - `UomConversionCreatedEvent` - Published when UomConversion is created
/// - `UomConversionUpdatedEvent` - Published when UomConversion is updated
/// - `UomConversionDeletedEvent` - Published when UomConversion is deleted
pub struct ExportSummary;
