//! Public services for Catalog module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These services provide the public API for other modules.
//! They only expose read operations - writes go through events.

use std::sync::Arc;

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use super::types::*;

// ============================================================================
// QUERY SERVICE TRAIT
// ============================================================================

/// Public query service for Catalog module
///
/// This trait defines read-only operations that other modules can use.
/// Implementations should NOT expose internal domain logic.
#[async_trait]
pub trait CatalogQueryService: Send + Sync {
    /// Get Attribute by ID
    async fn get_attribute(&self, id: AttributeId) -> Result<Option<AttributeDto>>;

    /// Get Attribute summary by ID
    async fn get_attribute_summary(&self, id: AttributeId) -> Result<Option<AttributeSummary>>;

    /// Check if Attribute exists
    async fn attribute_exists(&self, id: AttributeId) -> Result<bool>;

    /// Get AttributeValue by ID
    async fn get_attribute_value(&self, id: AttributeValueId) -> Result<Option<AttributeValueDto>>;

    /// Get AttributeValue summary by ID
    async fn get_attribute_value_summary(&self, id: AttributeValueId) -> Result<Option<AttributeValueSummary>>;

    /// Check if AttributeValue exists
    async fn attribute_value_exists(&self, id: AttributeValueId) -> Result<bool>;

    /// Get Brand by ID
    async fn get_brand(&self, id: BrandId) -> Result<Option<BrandDto>>;

    /// Get Brand summary by ID
    async fn get_brand_summary(&self, id: BrandId) -> Result<Option<BrandSummary>>;

    /// Check if Brand exists
    async fn brand_exists(&self, id: BrandId) -> Result<bool>;

    /// Get Item by ID
    async fn get_item(&self, id: ItemId) -> Result<Option<ItemDto>>;

    /// Get Item summary by ID
    async fn get_item_summary(&self, id: ItemId) -> Result<Option<ItemSummary>>;

    /// Check if Item exists
    async fn item_exists(&self, id: ItemId) -> Result<bool>;

    /// Get ItemGroup by ID
    async fn get_item_group(&self, id: ItemGroupId) -> Result<Option<ItemGroupDto>>;

    /// Get ItemGroup summary by ID
    async fn get_item_group_summary(&self, id: ItemGroupId) -> Result<Option<ItemGroupSummary>>;

    /// Check if ItemGroup exists
    async fn item_group_exists(&self, id: ItemGroupId) -> Result<bool>;

    /// Get ItemVariant by ID
    async fn get_item_variant(&self, id: ItemVariantId) -> Result<Option<ItemVariantDto>>;

    /// Get ItemVariant summary by ID
    async fn get_item_variant_summary(&self, id: ItemVariantId) -> Result<Option<ItemVariantSummary>>;

    /// Check if ItemVariant exists
    async fn item_variant_exists(&self, id: ItemVariantId) -> Result<bool>;

    /// Get Uom by ID
    async fn get_uom(&self, id: UomId) -> Result<Option<UomDto>>;

    /// Get Uom summary by ID
    async fn get_uom_summary(&self, id: UomId) -> Result<Option<UomSummary>>;

    /// Check if Uom exists
    async fn uom_exists(&self, id: UomId) -> Result<bool>;

    /// Get UomConversion by ID
    async fn get_uom_conversion(&self, id: UomConversionId) -> Result<Option<UomConversionDto>>;

    /// Get UomConversion summary by ID
    async fn get_uom_conversion_summary(&self, id: UomConversionId) -> Result<Option<UomConversionSummary>>;

    /// Check if UomConversion exists
    async fn uom_conversion_exists(&self, id: UomConversionId) -> Result<bool>;

}

// ============================================================================
// QUERY SERVICE IMPLEMENTATION
// ============================================================================

/// Default implementation of CatalogQueryService
pub struct CatalogQueryServiceImpl<R> {
    repository: Arc<R>,
}

impl<R> CatalogQueryServiceImpl<R> {
    pub fn new(repository: Arc<R>) -> Self {
        Self { repository }
    }
}

// ============================================================================
// CUSTOM SERVICES
// ============================================================================

// <<< CUSTOM SERVICES START >>>
// Add custom public services here
// <<< CUSTOM SERVICES END >>>
