//! Public types for Catalog module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These DTOs are the ONLY types other modules should use.
//! They are decoupled from internal domain entities.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;
use crate::domain::entity::*;

// ============================================================================
// ATTRIBUTE TYPES
// ============================================================================

/// Type-safe ID for Attribute
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct AttributeId(pub Uuid);

impl AttributeId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for AttributeId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<AttributeId> for Uuid {
    fn from(id: AttributeId) -> Self {
        id.0
    }
}

/// Data transfer object for Attribute
///
/// This is the public representation of Attribute for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AttributeDto {
    pub id: AttributeId,
    pub company_id: Uuid,
    pub code: String,
    pub name: String,
    pub attribute_type: AttributeType,
    pub status: CatalogStatus,
    pub metadata: serde_json::Value,
}

/// Summary view of Attribute for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AttributeSummary {
    pub id: AttributeId,
    pub name: String,
    pub status: CatalogStatus,
}

/// Reference to Attribute for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AttributeRef {
    pub id: AttributeId,
}

// ============================================================================
// ATTRIBUTEVALUE TYPES
// ============================================================================

/// Type-safe ID for AttributeValue
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct AttributeValueId(pub Uuid);

impl AttributeValueId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for AttributeValueId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<AttributeValueId> for Uuid {
    fn from(id: AttributeValueId) -> Self {
        id.0
    }
}

/// Data transfer object for AttributeValue
///
/// This is the public representation of AttributeValue for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AttributeValueDto {
    pub id: AttributeValueId,
    pub company_id: Uuid,
    pub attribute_id: Uuid,
    pub code: String,
    pub label: String,
    pub label_en: Option<String>,
    pub swatch_hex: Option<String>,
    pub icon: Option<String>,
    pub sort_order: i32,
    pub status: CatalogStatus,
    pub metadata: serde_json::Value,
}

/// Summary view of AttributeValue for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AttributeValueSummary {
    pub id: AttributeValueId,
    pub status: CatalogStatus,
}

/// Reference to AttributeValue for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AttributeValueRef {
    pub id: AttributeValueId,
}

// ============================================================================
// BRAND TYPES
// ============================================================================

/// Type-safe ID for Brand
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct BrandId(pub Uuid);

impl BrandId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for BrandId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<BrandId> for Uuid {
    fn from(id: BrandId) -> Self {
        id.0
    }
}

/// Data transfer object for Brand
///
/// This is the public representation of Brand for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BrandDto {
    pub id: BrandId,
    pub company_id: Uuid,
    pub code: String,
    pub name: String,
    pub short_description: Option<String>,
    pub description: Option<String>,
    pub logo_url: Option<String>,
    pub sort_order: i32,
    pub status: CatalogStatus,
    pub metadata: serde_json::Value,
}

/// Summary view of Brand for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BrandSummary {
    pub id: BrandId,
    pub name: String,
    pub status: CatalogStatus,
}

/// Reference to Brand for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BrandRef {
    pub id: BrandId,
}

// ============================================================================
// ITEM TYPES
// ============================================================================

/// Type-safe ID for Item
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ItemId(pub Uuid);

impl ItemId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for ItemId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<ItemId> for Uuid {
    fn from(id: ItemId) -> Self {
        id.0
    }
}

/// Data transfer object for Item
///
/// This is the public representation of Item for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ItemDto {
    pub id: ItemId,
    pub company_id: Uuid,
    pub item_code: String,
    pub name: String,
    pub description: Option<String>,
    pub barcode: Option<String>,
    pub brand_id: Option<Uuid>,
    pub item_group_id: Uuid,
    pub default_uom_id: Uuid,
    pub item_type: ItemType,
    pub is_sales_item: bool,
    pub is_purchase_item: bool,
    pub is_stock_item: bool,
    pub has_variants: bool,
    pub hsn_code: Option<String>,
    pub sni: Option<String>,
    pub is_taxable: bool,
    pub weight_per_unit: Option<Decimal>,
    pub shelf_life_days: Option<i32>,
    pub tags: serde_json::Value,
    pub data: serde_json::Value,
    pub status: CatalogStatus,
    pub metadata: serde_json::Value,
}

/// Summary view of Item for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ItemSummary {
    pub id: ItemId,
    pub name: String,
    pub status: CatalogStatus,
}

/// Reference to Item for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ItemRef {
    pub id: ItemId,
}

// ============================================================================
// ITEMGROUP TYPES
// ============================================================================

/// Type-safe ID for ItemGroup
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ItemGroupId(pub Uuid);

impl ItemGroupId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for ItemGroupId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<ItemGroupId> for Uuid {
    fn from(id: ItemGroupId) -> Self {
        id.0
    }
}

/// Data transfer object for ItemGroup
///
/// This is the public representation of ItemGroup for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ItemGroupDto {
    pub id: ItemGroupId,
    pub company_id: Uuid,
    pub code: String,
    pub name: String,
    pub parent_id: Option<Uuid>,
    pub is_group: bool,
    pub level: i32,
    pub sort_order: i32,
    pub status: CatalogStatus,
    pub metadata: serde_json::Value,
}

/// Summary view of ItemGroup for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ItemGroupSummary {
    pub id: ItemGroupId,
    pub name: String,
    pub status: CatalogStatus,
}

/// Reference to ItemGroup for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ItemGroupRef {
    pub id: ItemGroupId,
}

// ============================================================================
// ITEMVARIANT TYPES
// ============================================================================

/// Type-safe ID for ItemVariant
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ItemVariantId(pub Uuid);

impl ItemVariantId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for ItemVariantId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<ItemVariantId> for Uuid {
    fn from(id: ItemVariantId) -> Self {
        id.0
    }
}

/// Data transfer object for ItemVariant
///
/// This is the public representation of ItemVariant for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ItemVariantDto {
    pub id: ItemVariantId,
    pub company_id: Uuid,
    pub item_id: Uuid,
    pub sku: String,
    pub variant_label: String,
    pub options: serde_json::Value,
    pub barcode: Option<String>,
    pub is_default: bool,
    pub weight_per_unit: Option<Decimal>,
    pub status: CatalogStatus,
    pub metadata: serde_json::Value,
}

/// Summary view of ItemVariant for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ItemVariantSummary {
    pub id: ItemVariantId,
    pub status: CatalogStatus,
}

/// Reference to ItemVariant for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ItemVariantRef {
    pub id: ItemVariantId,
}

// ============================================================================
// UOM TYPES
// ============================================================================

/// Type-safe ID for Uom
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct UomId(pub Uuid);

impl UomId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for UomId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<UomId> for Uuid {
    fn from(id: UomId) -> Self {
        id.0
    }
}

/// Data transfer object for Uom
///
/// This is the public representation of Uom for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UomDto {
    pub id: UomId,
    pub company_id: Uuid,
    pub code: String,
    pub name: String,
    pub uom_type: UomType,
    pub decimal_places: i32,
    pub status: CatalogStatus,
    pub metadata: serde_json::Value,
}

/// Summary view of Uom for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UomSummary {
    pub id: UomId,
    pub name: String,
    pub status: CatalogStatus,
}

/// Reference to Uom for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UomRef {
    pub id: UomId,
}

// ============================================================================
// UOMCONVERSION TYPES
// ============================================================================

/// Type-safe ID for UomConversion
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct UomConversionId(pub Uuid);

impl UomConversionId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for UomConversionId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<UomConversionId> for Uuid {
    fn from(id: UomConversionId) -> Self {
        id.0
    }
}

/// Data transfer object for UomConversion
///
/// This is the public representation of UomConversion for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UomConversionDto {
    pub id: UomConversionId,
    pub company_id: Uuid,
    pub from_uom_id: Uuid,
    pub to_uom_id: Uuid,
    pub factor: Decimal,
    pub metadata: serde_json::Value,
}

/// Summary view of UomConversion for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UomConversionSummary {
    pub id: UomConversionId,
}

/// Reference to UomConversion for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UomConversionRef {
    pub id: UomConversionId,
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

// <<< CUSTOM TYPES START >>>
// Add custom public types here
// <<< CUSTOM TYPES END >>>
