//! Catalog Module
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

#![recursion_limit = "1024"]
#![allow(unused_imports)]

// Generated modules
pub mod domain;
pub mod infrastructure;
pub mod application;
pub mod presentation;
pub mod seeders;

// <<< CUSTOM
// metaphor-schema generates these files on disk but does not declare them in lib.rs
// (generator gap). Declared here inside a CUSTOM block so regeneration preserves the wiring.
pub mod handlers;   // AppState DI container (from_module / builder)
pub mod routes;     // stateless + stateful route composers over CatalogModule
pub mod exports;    // public cross-module API surface (DTOs, query service, events)
// END CUSTOM
// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::AttributeService;
pub use application::service::AttributeValueService;
pub use application::service::BrandService;
pub use application::service::ItemService;
pub use application::service::ItemGroupService;
pub use application::service::ItemVariantService;
pub use application::service::UomService;
pub use application::service::UomConversionService;

// <<< CUSTOM
pub use application::service::{
    CatalogWriteError, CatalogWriteService, NewAttribute, NewAttributeValue, NewBrand, NewItem,
    NewItemGroup, NewItemVariant, NewUom, NewUomConversion,
};
pub use presentation::http::create_guarded_catalog_routes;
// END CUSTOM
use std::sync::Arc;
use axum::Router;
use sqlx::PgPool;

/// Catalog module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let catalog = CatalogModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// // Unguarded full CRUD (trusted/admin); compose a guarded router for production.
/// let router = catalog.all_crud_routes();
/// ```
pub struct CatalogModule {
    pub attribute_service: Arc<AttributeService>,
    pub attribute_value_service: Arc<AttributeValueService>,
    pub brand_service: Arc<BrandService>,
    pub item_service: Arc<ItemService>,
    pub item_group_service: Arc<ItemGroupService>,
    pub item_variant_service: Arc<ItemVariantService>,
    pub uom_service: Arc<UomService>,
    pub uom_conversion_service: Arc<UomConversionService>,
    // <<< CUSTOM
    /// Validated Item/ItemGroup/UomConversion writes (FK existence, usage flags, factor>0).
    pub catalog_write_service: Arc<CatalogWriteService>,
    // END CUSTOM
}

impl CatalogModule {
    /// Create a new module builder
    pub fn builder() -> CatalogModuleBuilder {
        CatalogModuleBuilder::new()
    }

    /// Mount ALL generated CRUD endpoints (12 per entity) with NO domain
    /// validation — the fully **unguarded** surface. A well-formed request can
    /// create invalid rows or soft-delete a referenced master out from under its
    /// dependents. Prefer a guarded composition (read + validated writes) for any
    /// real deployment; use this only in trusted/admin/seeding contexts.
    pub fn all_crud_routes(&self) -> Router {
        use presentation::http::{
            create_attribute_routes,
            create_attribute_value_routes,
            create_brand_routes,
            create_item_routes,
            create_item_group_routes,
            create_item_variant_routes,
            create_uom_routes,
            create_uom_conversion_routes,
        };

        Router::new()
            .merge(create_attribute_routes(self.attribute_service.clone()))
            .merge(create_attribute_value_routes(self.attribute_value_service.clone()))
            .merge(create_brand_routes(self.brand_service.clone()))
            .merge(create_item_routes(self.item_service.clone()))
            .merge(create_item_group_routes(self.item_group_service.clone()))
            .merge(create_item_variant_routes(self.item_variant_service.clone()))
            .merge(create_uom_routes(self.uom_service.clone()))
            .merge(create_uom_conversion_routes(self.uom_conversion_service.clone()))
    }

    /// Deprecated alias for [`Self::all_crud_routes`]. `routes()` reads like
    /// "the routes" but mounts UNVALIDATED generic CRUD on every entity — a naive
    /// mount exposes unguarded writes. Compose a guarded router (read + validated
    /// writes) for production, or call `all_crud_routes()` to opt into the full
    /// unguarded surface explicitly.
    #[deprecated(note = "mounts unvalidated generic CRUD on every entity; compose a guarded router for production, or call all_crud_routes() for the intentional full/unguarded surface")]
    pub fn routes(&self) -> Router {
        self.all_crud_routes()
    }
}

/// Builder for CatalogModule
pub struct CatalogModuleBuilder {
    db_pool: Option<PgPool>,
}

impl CatalogModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    // <<< CUSTOM - custom builder methods
    // END CUSTOM

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<CatalogModule> {
        let db_pool = self.db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // Attribute service
        let attribute_repository = Arc::new(AttributeRepository::new(db_pool.clone()));
        let attribute_service = Arc::new(AttributeService::with_repository(attribute_repository.clone()));

        // AttributeValue service
        let attribute_value_repository = Arc::new(AttributeValueRepository::new(db_pool.clone()));
        let attribute_value_service = Arc::new(AttributeValueService::with_repository(attribute_value_repository.clone()));

        // Brand service
        let brand_repository = Arc::new(BrandRepository::new(db_pool.clone()));
        let brand_service = Arc::new(BrandService::with_repository(brand_repository.clone()));

        // Item service
        let item_repository = Arc::new(ItemRepository::new(db_pool.clone()));
        let item_service = Arc::new(ItemService::with_repository(item_repository.clone()));

        // ItemGroup service
        let item_group_repository = Arc::new(ItemGroupRepository::new(db_pool.clone()));
        let item_group_service = Arc::new(ItemGroupService::with_repository(item_group_repository.clone()));

        // ItemVariant service
        let item_variant_repository = Arc::new(ItemVariantRepository::new(db_pool.clone()));
        let item_variant_service = Arc::new(ItemVariantService::with_repository(item_variant_repository.clone()));

        // Uom service
        let uom_repository = Arc::new(UomRepository::new(db_pool.clone()));
        let uom_service = Arc::new(UomService::with_repository(uom_repository.clone()));

        // UomConversion service
        let uom_conversion_repository = Arc::new(UomConversionRepository::new(db_pool.clone()));
        let uom_conversion_service = Arc::new(UomConversionService::with_repository(uom_conversion_repository.clone()));

        // <<< CUSTOM
        let catalog_write_service = Arc::new(CatalogWriteService::new(db_pool.clone()));
        // END CUSTOM

        Ok(CatalogModule {
            attribute_service,
            attribute_value_service,
            brand_service,
            item_service,
            item_group_service,
            item_variant_service,
            uom_service,
            uom_conversion_service,
            // <<< CUSTOM
            catalog_write_service,
            // END CUSTOM
        })
    }
}

impl Default for CatalogModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}