//! Use case type aliases for Attribute aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateAttributeDto, UpdateAttributeDto};
use crate::application::service::AttributeService;
use crate::domain::entity::Attribute;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateAttributeUseCase = CreateUseCase<Attribute, CreateAttributeDto, AttributeService>;
pub type UpdateAttributeUseCase = UpdateUseCase<Attribute, UpdateAttributeDto, AttributeService>;
pub type GetAttributeUseCase    = GetUseCase<Attribute, AttributeService>;
pub type DeleteAttributeUseCase = DeleteUseCase<Attribute, AttributeService>;
pub type ListAttributeUseCase   = ListUseCase<Attribute, AttributeService>;

// <<< CUSTOM
// END CUSTOM
