//! Use case type aliases for AttributeValue aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateAttributeValueDto, UpdateAttributeValueDto};
use crate::application::service::AttributeValueService;
use crate::domain::entity::AttributeValue;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateAttributeValueUseCase = CreateUseCase<AttributeValue, CreateAttributeValueDto, AttributeValueService>;
pub type UpdateAttributeValueUseCase = UpdateUseCase<AttributeValue, UpdateAttributeValueDto, AttributeValueService>;
pub type GetAttributeValueUseCase    = GetUseCase<AttributeValue, AttributeValueService>;
pub type DeleteAttributeValueUseCase = DeleteUseCase<AttributeValue, AttributeValueService>;
pub type ListAttributeValueUseCase   = ListUseCase<AttributeValue, AttributeValueService>;

// <<< CUSTOM
// END CUSTOM
