//! Use case type aliases for Brand aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateBrandDto, UpdateBrandDto};
use crate::application::service::BrandService;
use crate::domain::entity::Brand;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateBrandUseCase = CreateUseCase<Brand, CreateBrandDto, BrandService>;
pub type UpdateBrandUseCase = UpdateUseCase<Brand, UpdateBrandDto, BrandService>;
pub type GetBrandUseCase    = GetUseCase<Brand, BrandService>;
pub type DeleteBrandUseCase = DeleteUseCase<Brand, BrandService>;
pub type ListBrandUseCase   = ListUseCase<Brand, BrandService>;

// <<< CUSTOM
// END CUSTOM
