//! Use case type aliases for Item aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateItemDto, UpdateItemDto};
use crate::application::service::ItemService;
use crate::domain::entity::Item;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateItemUseCase = CreateUseCase<Item, CreateItemDto, ItemService>;
pub type UpdateItemUseCase = UpdateUseCase<Item, UpdateItemDto, ItemService>;
pub type GetItemUseCase    = GetUseCase<Item, ItemService>;
pub type DeleteItemUseCase = DeleteUseCase<Item, ItemService>;
pub type ListItemUseCase   = ListUseCase<Item, ItemService>;

// <<< CUSTOM
// END CUSTOM
