//! Use case type aliases for ItemVariant aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateItemVariantDto, UpdateItemVariantDto};
use crate::application::service::ItemVariantService;
use crate::domain::entity::ItemVariant;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateItemVariantUseCase = CreateUseCase<ItemVariant, CreateItemVariantDto, ItemVariantService>;
pub type UpdateItemVariantUseCase = UpdateUseCase<ItemVariant, UpdateItemVariantDto, ItemVariantService>;
pub type GetItemVariantUseCase    = GetUseCase<ItemVariant, ItemVariantService>;
pub type DeleteItemVariantUseCase = DeleteUseCase<ItemVariant, ItemVariantService>;
pub type ListItemVariantUseCase   = ListUseCase<ItemVariant, ItemVariantService>;

// <<< CUSTOM
// END CUSTOM
