//! Use case type aliases for ItemGroup aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateItemGroupDto, UpdateItemGroupDto};
use crate::application::service::ItemGroupService;
use crate::domain::entity::ItemGroup;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateItemGroupUseCase = CreateUseCase<ItemGroup, CreateItemGroupDto, ItemGroupService>;
pub type UpdateItemGroupUseCase = UpdateUseCase<ItemGroup, UpdateItemGroupDto, ItemGroupService>;
pub type GetItemGroupUseCase    = GetUseCase<ItemGroup, ItemGroupService>;
pub type DeleteItemGroupUseCase = DeleteUseCase<ItemGroup, ItemGroupService>;
pub type ListItemGroupUseCase   = ListUseCase<ItemGroup, ItemGroupService>;

// <<< CUSTOM
// END CUSTOM
