//! Application use cases
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity contributes 5 type aliases (create, update, get, delete, list).

pub mod base;
pub use base::{UseCaseError, UseCaseResult, UseCaseHooks};

pub mod attribute_usecases;
pub mod attribute_value_usecases;
pub mod brand_usecases;
pub mod item_usecases;
pub mod item_group_usecases;
pub mod item_variant_usecases;
pub mod uom_usecases;
pub mod uom_conversion_usecases;

pub use attribute_usecases::{
    CreateAttributeUseCase, UpdateAttributeUseCase, GetAttributeUseCase,
    DeleteAttributeUseCase, ListAttributeUseCase,
};
pub use attribute_value_usecases::{
    CreateAttributeValueUseCase, UpdateAttributeValueUseCase, GetAttributeValueUseCase,
    DeleteAttributeValueUseCase, ListAttributeValueUseCase,
};
pub use brand_usecases::{
    CreateBrandUseCase, UpdateBrandUseCase, GetBrandUseCase,
    DeleteBrandUseCase, ListBrandUseCase,
};
pub use item_usecases::{
    CreateItemUseCase, UpdateItemUseCase, GetItemUseCase,
    DeleteItemUseCase, ListItemUseCase,
};
pub use item_group_usecases::{
    CreateItemGroupUseCase, UpdateItemGroupUseCase, GetItemGroupUseCase,
    DeleteItemGroupUseCase, ListItemGroupUseCase,
};
pub use item_variant_usecases::{
    CreateItemVariantUseCase, UpdateItemVariantUseCase, GetItemVariantUseCase,
    DeleteItemVariantUseCase, ListItemVariantUseCase,
};
pub use uom_usecases::{
    CreateUomUseCase, UpdateUomUseCase, GetUomUseCase,
    DeleteUomUseCase, ListUomUseCase,
};
pub use uom_conversion_usecases::{
    CreateUomConversionUseCase, UpdateUomConversionUseCase, GetUomConversionUseCase,
    DeleteUomConversionUseCase, ListUomConversionUseCase,
};

// <<< CUSTOM
// END CUSTOM
