//! Use case type aliases for UomConversion aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateUomConversionDto, UpdateUomConversionDto};
use crate::application::service::UomConversionService;
use crate::domain::entity::UomConversion;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateUomConversionUseCase = CreateUseCase<UomConversion, CreateUomConversionDto, UomConversionService>;
pub type UpdateUomConversionUseCase = UpdateUseCase<UomConversion, UpdateUomConversionDto, UomConversionService>;
pub type GetUomConversionUseCase    = GetUseCase<UomConversion, UomConversionService>;
pub type DeleteUomConversionUseCase = DeleteUseCase<UomConversion, UomConversionService>;
pub type ListUomConversionUseCase   = ListUseCase<UomConversion, UomConversionService>;

// <<< CUSTOM
// END CUSTOM
