//! Use case type aliases for Uom aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateUomDto, UpdateUomDto};
use crate::application::service::UomService;
use crate::domain::entity::Uom;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateUomUseCase = CreateUseCase<Uom, CreateUomDto, UomService>;
pub type UpdateUomUseCase = UpdateUseCase<Uom, UpdateUomDto, UomService>;
pub type GetUomUseCase    = GetUseCase<Uom, UomService>;
pub type DeleteUomUseCase = DeleteUseCase<Uom, UomService>;
pub type ListUomUseCase   = ListUseCase<Uom, UomService>;

// <<< CUSTOM
// END CUSTOM
