//! HTTP handlers
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! These handlers use Axum and backbone-core's BackboneCrudHandler
//! to provide all 12 standard Backbone CRUD endpoints.

pub mod attribute_handler;
pub mod attribute_value_handler;
pub mod brand_handler;
pub mod item_handler;
pub mod item_group_handler;
pub mod item_variant_handler;
pub mod uom_handler;
pub mod uom_conversion_handler;

// <<< CUSTOM
pub mod guarded_routes;
// END CUSTOM

// Re-exports
pub use attribute_handler::{create_attribute_routes, create_attribute_read_routes, create_attribute_write_routes};
pub use attribute_value_handler::{create_attribute_value_routes, create_attribute_value_read_routes, create_attribute_value_write_routes};
pub use brand_handler::{create_brand_routes, create_brand_read_routes, create_brand_write_routes};
pub use item_handler::{create_item_routes, create_item_read_routes, create_item_write_routes};
pub use item_group_handler::{create_item_group_routes, create_item_group_read_routes, create_item_group_write_routes};
pub use item_variant_handler::{create_item_variant_routes, create_item_variant_read_routes, create_item_variant_write_routes};
pub use uom_handler::{create_uom_routes, create_uom_read_routes, create_uom_write_routes};
pub use uom_conversion_handler::{create_uom_conversion_routes, create_uom_conversion_read_routes, create_uom_conversion_write_routes};
// <<< CUSTOM
pub use guarded_routes::create_guarded_catalog_routes;
// END CUSTOM